apiVersion: v1
kind: Pod
metadata:
  name: udmis-test-pod
spec:
  containers:
    - name: test-pod
      image: @IMAGE-udmis@
      resources:
        requests:
          cpu: 100m
          memory: 300Mi
      volumeMounts:
      - name: secret-volume
        mountPath: /udmi
        readOnly: true
      env:
      - name: UDMI_NAMESPACE
        valueFrom:
          configMapKeyRef:
            name: config
            key: UDMI_NAMESPACE
      - name: GCP_IOT_OPTIONS
        valueFrom:
          configMapKeyRef:
            name: config
            key: GCP_IOT_OPTIONS
  volumes:
    - name: secret-volume
      projected:
        sources:
        - secret:
            name: clearblade.json
    - name: tmp
      emptyDir:
        medium: Memory
    - name: var
      projected:
        sources:
        - configMap:
            name: config
