apiVersion: apps/v1
kind: Deployment
metadata:
  name: udmis-broker
  labels:
        app: mqttbroker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqttbroker
  template:
    metadata:
      labels:
        app: mqttbroker
    spec:
      containers:
      - name: broker-container
        image: hivemq/hivemq-ce
        resources:
          limits:
            memory: 600Mi
            cpu: 300m
          requests:
            memory: 200Mi
            cpu: 150m
        ports:
        - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: udmis-broker
spec:
  selector:
    app: mqttbroker
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
