#!/bin/bash -e

if [ $# != 1 ]; then
    echo Usage: $0 [project_id]
    false
fi

ROOT=$(realpath $(dirname $0)/..)
cd $ROOT/udms

PROJECT=$1
shift

version=`git describe --dirty`
echo Deploying version $version to $PROJECT
echo "const udmi_deploy_version = '$version';" > public/deploy_version.js

cat <<EOF > functions/version.js
module.exports = {
  udmis: '$version'
}
EOF

firebase use $PROJECT

only="functions:udmi_target"
only+=",functions:udmi_state"
only+=",functions:udmi_config"
only+=",functions:udmi_update"
only+=",functions:udmi_reflect"

echo firebase deploy --only $only
firebase deploy --only $only

echo
echo For local hosting: firebase serve --only hosting --project $PROJECT
echo Firestore address: https://console.cloud.google.com/firestore/data/?project=$PROJECT
echo Application host : https://$PROJECT.firebaseapp.com
echo
