#!/bin/bash -e

# This version is used to automatically check that the deployed cloud functions are suitable for any bit
# of client code. Clients (e.g. sqeuencer) can query this value and check that it's within range. Values
# indicate the MIN/MAX versions supported, while the client determines what is required.
FUNCTIONS_VERSION_MIN=2
FUNCTIONS_VERSION_MAX=2

if (( $# < 1 )); then
    echo Usage: $0 PROJECT_ID [options]
    false
fi

ROOT=$(realpath $(dirname $0)/..)
cd $ROOT/udmis

PROJECT=$1
shift

RUNTIME=nodejs16
SOURCE=functions/

deployed_by=$USER@$HOSTNAME
deployed_at=`date --utc --iso=seconds`
version=`git describe --dirty`
echo Deploying version $version to $PROJECT

cat <<EOF > functions/version.js
module.exports = {
  udmi_version: '$version',
  functions_min: $FUNCTIONS_VERSION_MIN,
  functions_max: $FUNCTIONS_VERSION_MAX,
  deployed_at: '$deployed_at',
  deployed_by: '$deployed_by'
}
EOF

PUBSUB_FUNCTIONS="udmi_target udmi_state udmi_config udmi_reflect"
for func in $PUBSUB_FUNCTIONS; do
    echo Deploying pubsub-trigger function $func...
    gcloud functions deploy $func --set-env-vars GCP_PROJECT=$PROJECT --trigger-topic=$func --runtime=$RUNTIME --project=$PROJECT --source=$SOURCE "$@" &
    sleep 10
done

echo Waiting for all deployments to complete...
wait

echo Done with deploying functions $PUBSUB_FUNCTIONS
