#!/bin/bash -e

# This version is used to automatically check that the deployed cloud functions are suitable for any bit
# of client code. Clients (e.g. sqeuencer) can query this value and check that it's within range.
FUNCTIONS_VERSION=1

if (( $# < 1 )); then
    echo Usage: $0 PROJECT_ID [options]
    false
fi

ROOT=$(realpath $(dirname $0)/..)
cd $ROOT/udmis

PROJECT=$1
shift

RUNTIME=nodejs16
SOURCE=functions/

version=`git describe --dirty`
echo Deploying version $version to $PROJECT

cat <<EOF > functions/version.js
module.exports = {
  udmis: '$version',
  functions: $FUNCTIONS_VERSION
}
EOF

PUBSUB_FUNCTIONS="udmi_target udmi_state udmi_config udmi_reflect"
for func in $PUBSUB_FUNCTIONS; do
    echo Deploying pubsub-trigger function $func...
    gcloud functions deploy $func --set-env-vars GCP_PROJECT=$PROJECT --trigger-topic=$func --runtime=$RUNTIME --project=$PROJECT --source=$SOURCE "$@" &
    sleep 10
done

echo Waiting for all deployments to complete...
wait

echo Done with deploying functions $PUBSUB_FUNCTIONS
