#!/bin/bash -e

if (( $# < 1 )); then
    echo Usage: $0 PROJECT_ID [options]
    false
fi

ROOT=$(realpath $(dirname $0)/..)
cd $ROOT/udmis

PROJECT=$1
shift

RUNTIME=nodejs16
SOURCE=functions/


deployed_by=$USER@$HOSTNAME
deployed_at=`date --utc --iso=seconds`
version=`git describe --dirty`
funchash=`git log -n 1 --oneline -- functions/ | awk '{print $1}'`
funccount=`git diff --name-only -- functions/ | wc -l`
if [[ $funccount != 0 ]]; then
    funcdirty=-dirty
fi
funcver=`git describe $funchash`$funcdirty

echo Deploying version $version to $PROJECT

cat <<EOF > functions/version.js
module.exports = {
  udmi_version: '$version',
  udmi_functions: '$funcver',
  deployed_at: '$deployed_at',
  deployed_by: '$deployed_by'
}
EOF

PUBSUB_FUNCTIONS="udmi_target udmi_state udmi_config udmi_reflect"
for func in $PUBSUB_FUNCTIONS; do
    echo Deploying pubsub-trigger function $func...
    gcloud functions deploy $func --set-env-vars GCP_PROJECT=$PROJECT --trigger-topic=$func --runtime=$RUNTIME --project=$PROJECT --source=$SOURCE "$@" &
    sleep 10
done

echo Waiting for all deployments to complete...
wait

echo Done with deploying functions $PUBSUB_FUNCTIONS
