apiVersion: v1
kind: Pod
metadata:
  name: udmi-test-pod
spec:
  containers:
    - name: test-pod
      image: gcr.io/bos-peringknife-dev/udmis
      imagePullPolicy: Always
      resources:
        requests:
          cpu: 100m
          memory: 99Mi
      volumeMounts:
        # name must match the volume name below
        - name: secret-volume
          mountPath: /udmi
          readOnly: true
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: pod-config.json
