apiVersion: v1
kind: Pod
metadata:
  name: udmi-test-pod
spec:
  containers:
    - name: test-pod
      image: gcr.io/@PROJECT@/udmis
      imagePullPolicy: Always
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      volumeMounts:
      - name: secret-volume
        mountPath: /udmi
        readOnly: true
  volumes:
    - name: secret-volume
      projected:
        sources:
        - secret:
            name: pod-config.json
        - secret:
            name: clearblade.json
            optional: true
