apiVersion: apps/v1
kind: Deployment
metadata:
  name: udmis-pod
spec:
  selector:
    matchLabels:
      app: udmis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: udmis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: gcr.io/@PROJECT@/udmis
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        # name must match the volume name below
        - name: secret-volume
          mountPath: /udmi
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: pod-config.json
