#!/bin/bash -e
# Creates reflector credentials and device entry in UDMS-REFLECT for a site
#
# Usage: create_reflect_credentials PATH_TO_SITE_MODEL PROJECT_ID

if [[ "$#" != 2 ]]; then
    echo $0 SITE_MODEL PROJECT_ID
    exit 1
fi
SITE_MODEL=$1
PROJECT_ID=$2
shift 2

ROOT_DIR=$(git rev-parse --show-toplevel)

registry_id=$(jq -r .registry_id $SITE_MODEL/cloud_iot_config.json)
cloud_region=$(jq -r .cloud_region $SITE_MODEL/cloud_iot_config.json)

if [[ -f $SITE_MODEL/validator/rsa_private.pkcs8 ]]; then
    echo validator credentials seem to already exist, exitting ..
    exit 1
fi

mkdir -p $SITE_MODEL/validator
$ROOT_DIR/bin/keygen RS256 $SITE_MODEL/validator

gcloud iot devices create $registry_id --region=us-central1 --registry=UDMS-REFLECT --project=$PROJECT_ID \
    --public-key \
        path=$SITE_MODEL/validator/rsa_public.pem,type=RSA_PEM
