FROM debian:12-slim

WORKDIR /root

RUN apt-get update && \
    apt-get install --no-install-suggests --no-install-recommends --yes python3-venv gcc libpython3-dev sudo && \
    python3 -m venv venv && \
    venv/bin/pip install --upgrade pip setuptools wheel

ADD discoverynode/src/requirements.txt /tmp/
RUN venv/bin/pip install --disable-pip-version-check -r /tmp/requirements.txt
ADD discoverynode/ discoverynode/
