FROM debian:12-slim

COPY discoverynode/ /root/discoverynode/
WORKDIR /root/discoverynode

RUN apt-get update && \
    apt-get install --no-install-suggests --no-install-recommends --yes python3-venv gcc libpython3-dev sudo jq moreutils && \
    python3 -m venv venv && \
    venv/bin/pip install --upgrade pip setuptools wheel

RUN venv/bin/pip install --disable-pip-version-check -r src/requirements.txt
