./update_site.sh  CA-WAT-BRT1
./update_site.sh  CA-WAT-BRT2
./update_site.sh  US-ARB-TRAV
./update_site.sh  US-AUS-500W
./update_site.sh  US-BLD-2600
./update_site.sh  US-BLD-PEA
./update_site.sh  US-BOT-NCN
./update_site.sh  US-CHI-FLMK
./update_site.sh  US-DTW-EHENRY52
./update_site.sh  US-IRV-FAIR
./update_site.sh  US-IRV-JAMB19520
./update_site.sh  US-KIR-6THA
./update_site.sh  US-KIR-6THB
./update_site.sh  US-KIR-6THD
./update_site.sh  US-KIR-CWP
./update_site.sh  US-KIR-KUC
./update_site.sh  US-KIR-KUN
./update_site.sh  US-LAX-BIN1
./update_site.sh  US-LVK-7633
./update_site.sh  US-MFA-BV100
./update_site.sh  US-MFA-BV200
./update_site.sh  US-MFA-BV300
./update_site.sh  US-MFA-BV400
./update_site.sh  US-MFA-BV500
./update_site.sh  US-MTV-1015
./update_site.sh  US-MTV-1055
./update_site.sh  US-MTV-1098
./update_site.sh  US-MTV-1157
./update_site.sh  US-MTV-1161
./update_site.sh  US-MTV-1200
./update_site.sh  US-MTV-1201
./update_site.sh  US-MTV-1210
./update_site.sh  US-MTV-1215
./update_site.sh  US-MTV-1220
./update_site.sh  US-MTV-1225
./update_site.sh  US-MTV-1230
./update_site.sh  US-MTV-1245
./update_site.sh  US-MTV-1250
./update_site.sh  US-MTV-1295
./update_site.sh  US-MTV-1300
./update_site.sh  US-MTV-1350
./update_site.sh  US-MTV-1395
./update_site.sh  US-MTV-1489
./update_site.sh  US-MTV-1600
./update_site.sh  US-MTV-1616
./update_site.sh  US-MTV-1625
./update_site.sh  US-MTV-1667
./update_site.sh  US-MTV-1674
./update_site.sh  US-MTV-1675
./update_site.sh  US-MTV-1685
./update_site.sh  US-MTV-1708
./update_site.sh  US-MTV-1758
./update_site.sh  US-MTV-1804
./update_site.sh  US-MTV-1808
./update_site.sh  US-MTV-1842
./update_site.sh  US-MTV-1875
./update_site.sh  US-MTV-1900
./update_site.sh  US-MTV-1945
./update_site.sh  US-MTV-1950
./update_site.sh  US-MTV-1965
./update_site.sh  US-MTV-2000
./update_site.sh  US-MTV-2011
./update_site.sh  US-MTV-2015
./update_site.sh  US-MTV-2017
./update_site.sh  US-MTV-2071
./update_site.sh  US-MTV-2081
./update_site.sh  US-MTV-2171
./update_site.sh  US-MTV-2637
./update_site.sh  US-MTV-2644
./update_site.sh  US-MTV-2690
./update_site.sh  US-MTV-2700
./update_site.sh  US-MTV-2751
./update_site.sh  US-MTV-325
./update_site.sh  US-MTV-40
./update_site.sh  US-MTV-41
./update_site.sh  US-MTV-42
./update_site.sh  US-MTV-43
./update_site.sh  US-MTV-44
./update_site.sh  US-MTV-45
./update_site.sh  US-MTV-46
./update_site.sh  US-MTV-47
./update_site.sh  US-MTV-48
./update_site.sh  US-MTV-900
./update_site.sh  US-MTV-918R
./update_site.sh  US-MTV-946
./update_site.sh  US-MTV-ALTAPSA
./update_site.sh  US-MTV-BAYSH2598
./update_site.sh  US-MTV-C440
./update_site.sh  US-MTV-C450
./update_site.sh  US-MTV-C500
./update_site.sh  US-MTV-CE
./update_site.sh  US-MTV-CL2
./update_site.sh  US-MTV-CL3
./update_site.sh  US-MTV-CL4
./update_site.sh  US-MTV-CL5
./update_site.sh  US-MTV-CYD1
./update_site.sh  US-MTV-E401
./update_site.sh  US-MTV-E475
./update_site.sh  US-MTV-E501
./update_site.sh  US-MTV-E515
./update_site.sh  US-MTV-FRC1
./update_site.sh  US-MTV-FRC2
./update_site.sh  US-MTV-GWC1
./update_site.sh  US-MTV-GWC2
./update_site.sh  US-MTV-GWC3
./update_site.sh  US-MTV-GWC4
./update_site.sh  US-MTV-GWC5
./update_site.sh  US-MTV-GWC6
./update_site.sh  US-MTV-GWC7
./update_site.sh  US-MTV-L441
./update_site.sh  US-MTV-L500
./update_site.sh  US-MTV-LMK2
./update_site.sh  US-MTV-LMK5
./update_site.sh  US-MTV-M800
./update_site.sh  US-MTV-PLY1
./update_site.sh  US-MTV-PLY2
./update_site.sh  US-MTV-PLYM1625
./update_site.sh  US-MTV-PR55
./update_site.sh  US-MTV-QD1
./update_site.sh  US-MTV-QD2
./update_site.sh  US-MTV-QD3
./update_site.sh  US-MTV-QD4
./update_site.sh  US-MTV-QD5
./update_site.sh  US-MTV-QD6
./update_site.sh  US-MTV-QD7
./update_site.sh  US-MTV-RLS1
./update_site.sh  US-MTV-RLS2
./update_site.sh  US-MTV-SB10
./update_site.sh  US-MTV-SB30
./update_site.sh  US-MTV-SB45
./update_site.sh  US-MTV-SB50
./update_site.sh  US-MTV-SB55
./update_site.sh  US-MTV-SB65
./update_site.sh  US-MTV-SB71
./update_site.sh  US-MTV-SB75
./update_site.sh  US-MTV-SB80
./update_site.sh  US-MTV-SB83
./update_site.sh  US-MTV-SB90
./update_site.sh  US-MTV-SB93
./update_site.sh  US-MTV-SL00
./update_site.sh  US-MTV-SL1001
./update_site.sh  US-MTV-SP40
./update_site.sh  US-MTV-SP50
./update_site.sh  US-MTV-STLN2019
./update_site.sh  US-MTV-STLN2025
./update_site.sh  US-MTV-STLN2027
./update_site.sh  US-MTV-STLN2029
./update_site.sh  US-MTV-STLN2051
./update_site.sh  US-MTV-STLN2061
./update_site.sh  US-MTV-TB44
./update_site.sh  US-MTV-TB55
./update_site.sh  US-NYC-8510
./update_site.sh  US-NYC-9TH
./update_site.sh  US-NYC-HUD345
./update_site.sh  US-PAO-1010
./update_site.sh  US-PAO-1129
./update_site.sh  US-PAO-1137
./update_site.sh  US-PAO-3801
./update_site.sh  US-PAO-EM15
./update_site.sh  US-PAO-EM25
./update_site.sh  US-PAO-EM40
./update_site.sh  US-PAO-EM86
./update_site.sh  US-PAO-EM935
./update_site.sh  US-PAO-HV1
./update_site.sh  US-PAO-HV2
./update_site.sh  US-PAO-HV3
./update_site.sh  US-PAO-HV4
./update_site.sh  US-PAO-HV5
./update_site.sh  US-PAO-MIR1
./update_site.sh  US-PAO-MIR3
./update_site.sh  US-PIT-BAK2
./update_site.sh  US-PLV-H15
./update_site.sh  US-RED-DBHQ
./update_site.sh  US-RES-REST1900
./update_site.sh  US-RWC-SEA2
./update_site.sh  US-RWC-SEA3
./update_site.sh  US-RWC-SEA6
./update_site.sh  US-RWC-SEA9
./update_site.sh  US-SAN-6420
./update_site.sh  US-SBO-1000
./update_site.sh  US-SBO-1100
./update_site.sh  US-SBO-1250
./update_site.sh  US-SBO-900
./update_site.sh  US-SBO-901
./update_site.sh  US-SBO-999
./update_site.sh  US-SFO-1MST
./update_site.sh  US-SFO-FRE215
./update_site.sh  US-SFO-MKT1
./update_site.sh  US-SJC-BNV1
./update_site.sh  US-SJC-BNV2
./update_site.sh  US-SJC-DISK5087
./update_site.sh  US-SJC-DISK5093
./update_site.sh  US-SJC-TM1
./update_site.sh  US-SJC-TM2
./update_site.sh  US-SJC-TM3
./update_site.sh  US-SVL-494
./update_site.sh  US-SVL-BORD1185
./update_site.sh  US-SVL-BORD1212
./update_site.sh  US-SVL-BRG1
./update_site.sh  US-SVL-BRGAS1265
./update_site.sh  US-SVL-CRSM1225
./update_site.sh  US-SVL-CRSM1240
./update_site.sh  US-SVL-CRSM1249
./update_site.sh  US-SVL-CRSM1260
./update_site.sh  US-SVL-CRSM1265
./update_site.sh  US-SVL-CSPN222
./update_site.sh  US-SVL-HMBLT1
./update_site.sh  US-SVL-HMBLT2
./update_site.sh  US-SVL-HMBLT3
./update_site.sh  US-SVL-HMBLT4
./update_site.sh  US-SVL-JAVA111
./update_site.sh  US-SVL-MAT1
./update_site.sh  US-SVL-MAT2
./update_site.sh  US-SVL-MAT3
./update_site.sh  US-SVL-MOT1
./update_site.sh  US-SVL-MP1
./update_site.sh  US-SVL-MP2
./update_site.sh  US-SVL-MP3
./update_site.sh  US-SVL-MP4
./update_site.sh  US-SVL-MP5
./update_site.sh  US-SVL-MP6
./update_site.sh  US-SVL-MP7
./update_site.sh  US-SVL-MPD217
./update_site.sh  US-SVL-MPD237
./update_site.sh  US-SVL-TC1
./update_site.sh  US-SVL-TC2
./update_site.sh  US-SVL-TC3
./update_site.sh  US-SVL-TC4
./update_site.sh  US-SVL-TC5
./update_site.sh  US-SVL-TC6
./update_site.sh  US-SVL-TC7
./update_site.sh  US-SVQ-AIRWY5665