apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciler-service
spec:
  selector:
    matchLabels:
      app: reconciler-service
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: reconciler-service
        role: master
        tier: backend
    spec:
      containers:
      - name: reconciler-core
        image: @IMAGE@
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        env:
        - name: UDMI_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: config
              key: UDMI_NAMESPACE
              optional: true
