apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciler-service
spec:
  selector:
    matchLabels:
      app: reconciler-service
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: reconciler-service
        role: master
        tier: backend
    spec:
      containers:
      - name: reconciler-core
        image: @IMAGE@
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        env:
        - name: UDMI_NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: config
              key: UDMI_NAMESPACE
              optional: true
        command: [ "/bin/sh", "-c" ]
        args:
        - |
          set -eu

          GCP_PROJECT=$(curl -s "http://metadata.google.internal/computeMetadata/v1/project/project-id" -H "Metadata-Flavor: Google")

          echo "Starting process in project ${GCP_PROJECT} in namespace $UDMI_NAMESPACE"

          if [ -n "$UDMI_NAMESPACE" ]; then
            NAMESPACE_PATH="/$UDMI_NAMESPACE"
          else
            NAMESPACE_PATH=""
          fi

          exec /root/services/bin/reconciler_service \
            "//pubsub/${GCP_PROJECT}${NAMESPACE_PATH}" \
            "/tmp/udmi/sites"
