# generated by datamodel-codegen:
#   filename:  building_config_entity.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class BuildingConfigEntity(DataModel):
    code: Optional[str] = None
    etag: Optional[str] = None
    type: Optional[str] = None
