# generated by datamodel-codegen:
#   filename:  commands_mapping.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .entry import Entry
from .equipment_translation import BuildingConfig


@dataclass
class MappingCommand(DataModel):
    """
    [Mapping command](../docs/specs/mapping.md) for provisioning
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    guid: Optional[str] = None
    device_num_id: Optional[float] = None
    status: Optional[Entry] = None
    translation: Optional[BuildingConfig] = None
