# generated by datamodel-codegen:
#   filename:  configuration_execution.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from ._base import DataModel
from .common import IotProvider
from .config_mapping import MappingConfig
from .configuration_endpoint import EndpointConfiguration


@dataclass
class ExecutionConfiguration(DataModel):
    """
    Parameters for configuring the execution run of a UDMI tool
    """

    registry_id: Optional[str] = None
    cloud_region: Optional[str] = None
    site_name: Optional[str] = None
    update_topic: Optional[str] = None
    feed_name: Optional[str] = None
    reflect_region: Optional[str] = None
    site_model: Optional[str] = None
    src_file: Optional[str] = None
    registry_suffix: Optional[str] = None
    shard_count: Optional[int] = None
    shard_index: Optional[int] = None
    device_id: Optional[str] = None
    iot_provider: Optional[IotProvider] = None
    reflector_endpoint: Optional[EndpointConfiguration] = None
    device_endpoint: Optional[EndpointConfiguration] = None
    project_id: Optional[str] = None
    user_name: Optional[str] = None
    udmi_namespace: Optional[str] = None
    bridge_host: Optional[str] = None
    key_file: Optional[str] = None
    serial_no: Optional[str] = None
    log_level: Optional[str] = None
    min_stage: Optional[str] = None
    udmi_version: Optional[str] = None
    udmi_commit: Optional[str] = None
    udmi_ref: Optional[str] = None
    udmi_timever: Optional[str] = None
    enforce_version: Optional[bool] = None
    udmi_root: Optional[str] = None
    update_to: Optional[str] = None
    alt_project: Optional[str] = None
    alt_registry: Optional[str] = None
    block_unknown: Optional[bool] = None
    sequences: Optional[List[str]] = None
    mapping_configuration: Optional[MappingConfig] = None
