# generated by datamodel-codegen:
#   filename:  configuration_pod_base.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class BasePodConfiguration(DataModel):
    """
    Parameters to define pod base parameters
    """

    udmi_prefix: Optional[str] = None
    failure_rate: Optional[float] = None
