# generated by datamodel-codegen:
#   filename:  configuration_pod.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .access_iot import IotAccess
from .configuration_endpoint import EndpointConfiguration
from .configuration_pod_base import BasePodConfiguration
from .configuration_pod_bridge import BridgePodConfiguration


@dataclass
class PodConfiguration(DataModel):
    """
    Parameters for configuring the execution run of a UDMIS pod
    """

    include: Optional[str] = None
    base: Optional[BasePodConfiguration] = None
    flow_defaults: Optional[EndpointConfiguration] = None
    crons: Optional[Dict[str, EndpointConfiguration]] = None
    flows: Optional[Dict[str, EndpointConfiguration]] = None
    bridges: Optional[Dict[str, BridgePodConfiguration]] = None
    iot_access: Optional[Dict[str, IotAccess]] = None
    iot_data: Optional[Dict[str, IotAccess]] = None
