# generated by datamodel-codegen:
#   filename:  discovery_ref.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

from ._base import DataModel
from .ancillary_properties import AncillaryProperties
from .discovery_family import FamilyDiscovery
from .entry import Entry


@dataclass
class Structure(DataModel):
    point: Optional[FamilyDiscovery] = None
    families: Optional[Dict[str, FamilyDiscovery]] = None


@dataclass
class RefDiscovery(DataModel):
    """
    Object representation for for a single point reference discovery
    """

    point: Optional[str] = None
    name: Optional[str] = None
    possible_values: Optional[List[str]] = None
    units: Optional[str] = None
    ref: Optional[str] = None
    type: Optional[str] = None
    writable: Optional[bool] = None
    description: Optional[str] = None
    status: Optional[Entry] = None
    ancillary: Optional[AncillaryProperties] = None
    adjunct: Optional[Dict[str, str]] = None
    structure: Optional[Structure] = None
