# generated by datamodel-codegen:
#   filename:  model_gateway.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from ._base import DataModel
from .model_localnet_family import FamilyLocalnetModel


@dataclass
class GatewayModel(DataModel):
    """
    [Gateway Documentation](../docs/specs/gateway.md)
    """

    gateway_id: Optional[str] = None
    target: Optional[FamilyLocalnetModel] = None
    proxy_ids: Optional[List[str]] = None
