# generated by datamodel-codegen:
#   filename:  model_externals.json

from __future__ import annotations

from typing import Dict, Optional

from ._base import DataModel
from .model_externals_link import LinkExternalsModel

ExternalsModel = Optional[Dict[str, LinkExternalsModel]]
