# generated by datamodel-codegen:
#   filename:  model_features.json

from __future__ import annotations

from typing import Dict, Optional

from ._base import DataModel
from .discovery_feature import FeatureDiscovery

TestingModel = Optional[Dict[str, FeatureDiscovery]]
