# generated by datamodel-codegen:
#   filename:  state_gateway.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .entry import Entry


@dataclass
class GatewayState(DataModel):
    """
    [Gateway Documentation](../docs/specs/gateway.md)
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    status: Optional[Entry] = None
