# generated by datamodel-codegen:
#   filename:  state_validation_schema.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional

from ._base import DataModel
from .state_validation_sequence import SequenceValidationState


@dataclass
class SchemaValidationState(DataModel):
    """
    Schema validation state
    """

    stages: Optional[Dict[str, Any]] = None
    sequences: Optional[Dict[str, SequenceValidationState]] = None
