# generated by datamodel-codegen:
#   filename:  state_discovery.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .state_discovery_family import FamilyDiscoveryState


@dataclass
class DiscoveryState(DataModel):
    """
    State for [discovery](../docs/specs/discovery.md)
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    generation: Optional[str] = None
    families: Optional[Dict[str, FamilyDiscoveryState]] = None
