# generated by datamodel-codegen:
#   filename:  state_blobset.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .state_blobset_blob import BlobBlobsetState


@dataclass
class BlobsetState(DataModel):
    blobs: Optional[Dict[str, BlobBlobsetState]] = None
