# generated by datamodel-codegen:
#   filename:  state_validation.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

from ._base import DataModel
from .config_udmi import Setup
from .entry import Entry
from .events_validation_device import DeviceValidationEvents
from .state_validation_feature import FeatureValidationState
from .state_validation_schema import SchemaValidationState


@dataclass
class Summary(DataModel):
    correct_devices: Optional[List[str]] = None
    extra_devices: Optional[List[str]] = None
    missing_devices: Optional[List[str]] = None
    error_devices: Optional[List[str]] = None


@dataclass
class ValidationState(DataModel):
    """
    Validation state summary
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    cloud_version: Optional[Setup] = None
    udmi_version: Optional[str] = None
    last_updated: Optional[str] = None
    start_time: Optional[str] = None
    status: Optional[Entry] = None
    features: Optional[Dict[str, FeatureValidationState]] = None
    schemas: Optional[Dict[str, SchemaValidationState]] = None
    summary: Optional[Summary] = None
    devices: Optional[Dict[str, DeviceValidationEvents]] = None
