[mqtt]
device_id = "AHU-1"
host = "mqtt-dev.bos.goog"
port = 8883
registry_id = "ZZ-TRI-FECTA"
region = "us-central1"
project_id = "bos-platform-testing"
key_file = "/usr/src/app/rsa_private.pem"
algorithm = "RS256"

[nmap]
targets = ["127.0.0.1"]
interface = "eth0"

[bacnet]
ip = "127.0.0.1/32"
