FROM alpine:latest

WORKDIR /root

# Ideally the same as from Dockerfile.udmis to share layers
RUN apk add bash openjdk17 gcompat curl jq sudo git mosquitto mosquitto-clients openssl coreutils

# And other stuff not in Dockerfile.udmis
RUN apk add python3 moreutils

ADD build/udmi_bin/ bin/
ADD build/udmi_etc/ etc/
ADD build/schema/ schema/
RUN bin/setup_base

ADD bin/ validator/bin/
ADD build/libs validator/build/libs/

CMD ["/root/validator/bin/automate"]
