FROM alpine:latest

WORKDIR /root

RUN apk add openjdk17 bash gcompat mosquitto-clients curl jq

# Workaround for https://github.com/grpc/grpc-java/issues/8751
ENV LD_PRELOAD=/lib/libgcompat.so.0

ADD build/libs/validator-1.0-SNAPSHOT-all.jar build/libs/validator-1.0-SNAPSHOT-all.jar

ADD bin/ bin/

CMD ["/root/bin/automate"]
