#!/bin/bash -e

if [ $# != 1 ]; then
    echo Usage: $0 [project_id]
    false
fi

ROOT=$(realpath $(dirname $0)/..)
cd $ROOT/dashboard

PROJECT=$1
shift

RUNTIME=nodejs12
SOURCE=functions/

version=`git describe --dirty`
echo Deploying version $version to $PROJECT
echo "const udmi_deploy_version = '$version';" > public/deploy_version.js

cat <<EOF > functions/version.js
module.exports = {
  udmis: '$version'
}
EOF

PUBSUB_FUNCTIONS="udmi_target udmi_state udmi_config udmi_reflect"
for func in $PUBSUB_FUNCTIONS; do
    echo Deploying pubsub-trigger function $func...
    gcloud functions deploy $func --set-env-vars GCP_PROJECT=$PROJECT --trigger-topic=$func --runtime=$RUNTIME --project=$PROJECT --source=$SOURCE &
    sleep 10
done

echo Waiting for all deployments to complete...
wait

echo Skipped deploy of udmi_update b/c it requires firebase.
echo Done with deploying functions $PUBSUB_FUNCTIONS
