#!/bin/bash -e

if [ $# != 1 ]; then
    echo Usage: $0 [project_id]
    false
fi

ROOT=$(realpath $(dirname $0)/..)
cd $ROOT/dashboard

PROJECT=$1
shift

version=`git describe --dirty`
echo Deploying version $version to $PROJECT
echo "const udmi_deploy_version = '$version';" > public/deploy_version.js

firebase use $PROJECT

echo firebase deploy --project $PROJECT
firebase deploy --project $PROJECT

echo
echo For local hosting: firebase serve --only hosting --project $PROJECT
echo Firestore address: https://console.cloud.google.com/firestore/data/?project=$PROJECT
echo Application host : https://$PROJECT.firebaseapp.com
echo
