# generated by datamodel-codegen:
#   filename:  access_iot.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .common import IotProvider


@dataclass
class IotAccess(DataModel):
    name: Optional[str] = None
    provider: Optional[IotProvider] = None
    project_id: Optional[str] = None
    profile_sec: Optional[int] = None
    options: Optional[str] = None
