# generated by datamodel-codegen:
#   filename:  alarm_ack.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class AlarmAcknowledgement(DataModel):
    """
    Details about an alarm acknowledgement
    """

    timestamp: Optional[str] = None
    user: Optional[str] = None
    comment: Optional[str] = None
