# generated by datamodel-codegen:
#   filename:  ancillary_properties.json

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class AncillaryProperties:
    """
    Arbitrary blob of json associated with this point
    """
