# generated by datamodel-codegen:
#   filename:  ancillary_properties.json

from __future__ import annotations

from dataclasses import dataclass

from ._base import DataModel


@dataclass
class AncillaryProperties(DataModel):
    """
    Arbitrary blob of json associated with this point
    """
