# generated by datamodel-codegen:
#   filename:  ancillary_properties.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from pydantic import BaseModel


class AncillaryProperties(BaseModel):
    """
    Arbitrary blob of json associated with this point
    """
