# generated by datamodel-codegen:
#   filename:  building_translation.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel


@dataclass
class Units(DataModel):
    key: Optional[str] = None
    values: Optional[Dict[str, str]] = None


@dataclass
class BuildingTranslation(DataModel):
    """
    [Discovery result](../docs/specs/discovery.md) with implicit enumeration
    """

    present_value: Optional[str] = None
    units: Optional[Units] = None
    states: Optional[Dict[str, str]] = None
