# generated by datamodel-codegen:
#   filename:  commands_discovery.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class DiscoveryCommand(DataModel):
    """
    [Discovery command](../docs/specs/discovery.md) for provisioning
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
