# generated by datamodel-codegen:
#   filename:  commands_mapping.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .entry import Entry
from .equipment_translation import BuildingConfig


class MappingCommand(BaseModel):
    """
    [Mapping command](../docs/specs/mapping.md) for provisioning
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='RFC 3339 UTC timestamp the configuration was generated',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
    guid: Optional[str] = Field(None, description='device guid')
    device_num_id: Optional[float] = Field(
        None, description='numerical id assigned to this device'
    )
    status: Optional[Entry] = None
    translation: Optional[BuildingConfig] = None
