# generated by datamodel-codegen:
#   filename:  config_system.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .common import Mode
from .config_system_testing import TestingSystemConfig


@dataclass
class Operation(DataModel):
    mode: Optional[Mode] = None
    last_start: Optional[str] = None


@dataclass
class SystemConfig(DataModel):
    """
    [System Config Documentation](../docs/messages/system.md#config)
    """

    min_loglevel: Optional[int] = 300
    metrics_rate_sec: Optional[int] = 10
    operation: Optional[Operation] = None
    testing: Optional[TestingSystemConfig] = None
