# generated by datamodel-codegen:
#   filename:  configuration_endpoint.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, Optional

from ._base import DataModel


class Protocol(Enum):
    local = 'local'
    pubsub = 'pubsub'
    file = 'file'
    trace = 'trace'
    mqtt = 'mqtt'


class Transport(Enum):
    ssl = 'ssl'
    tcp = 'tcp'


@dataclass
class Basic(DataModel):
    username: Optional[str] = None
    password: Optional[str] = None


@dataclass
class Jwt(DataModel):
    audience: Optional[str] = None


@dataclass
class AuthProvider(DataModel):
    basic: Optional[Basic] = None
    jwt: Optional[Jwt] = None


@dataclass
class EndpointConfiguration(DataModel):
    """
    Parameters to define a message endpoint
    """

    name: Optional[str] = None
    protocol: Optional[Protocol] = None
    transport: Optional[Transport] = None
    hostname: Optional[str] = None
    payload: Optional[str] = None
    error: Optional[str] = None
    port: Optional[int] = None
    config_sync_sec: Optional[int] = None
    client_id: Optional[str] = None
    topic_prefix: Optional[str] = None
    recv_id: Optional[str] = None
    send_id: Optional[str] = None
    side_id: Optional[str] = None
    gatewayId: Optional[str] = None
    deviceId: Optional[str] = None
    enabled: Optional[str] = None
    noConfigAck: Optional[bool] = None
    capacity: Optional[int] = None
    publish_delay_sec: Optional[int] = None
    periodic_sec: Optional[int] = None
    keyBytes: Optional[Any] = None
    algorithm: Optional[str] = None
    auth_provider: Optional[AuthProvider] = None
    generation: Optional[str] = None
