# generated by datamodel-codegen:
#   filename:  config_system.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, conint

from .common import Mode
from .config_system_testing import TestingSystemConfig


class Operation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mode: Optional[Mode] = None
    last_start: Optional[datetime] = Field(
        None,
        description='Last time a device with this id said it restarted: being later than status-supplied last_start indicates resource conflict.',
    )


class SystemConfig(BaseModel):
    """
    [System Config Documentation](../docs/messages/system.md#config)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    min_loglevel: Optional[conint(ge=100, le=800)] = Field(
        300,
        description='The minimum loglevel for reporting log messages below which log entries should not be sent. Default to 300.',
    )
    metrics_rate_sec: Optional[conint(ge=0, le=86400)] = Field(
        10,
        description='The rate at which the system should send system event updates. 0 indicates no updates.',
    )
    operation: Optional[Operation] = None
    testing: Optional[TestingSystemConfig] = None
