# generated by datamodel-codegen:
#   filename:  config_localnet_family.json

from __future__ import annotations

from dataclasses import dataclass

from ._base import DataModel


@dataclass
class FamilyLocalnetConfig(DataModel):
    pass
