# generated by datamodel-codegen:
#   filename:  config_system_testing.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class TestingSystemConfig(BaseModel):
    """
    Configuration parameters for device-under-test
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    sequence_name: Optional[str] = Field(
        None, description='The sequence name currently being tested (for debug logging)'
    )
    transaction_id: Optional[str] = Field(
        None, description='The transaction id used to generate this config update'
    )
    config_base: Optional[int] = Field(
        None, description='The configuration version that this update was based on'
    )
    endpoint_type: Optional[str] = Field(
        None, description='Designator for the kind of endpoint being used for this test'
    )
