# generated by datamodel-codegen:
#   filename:  config_pointset_point.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional

from ._base import DataModel


@dataclass
class PointPointsetConfig(DataModel):
    ref: Optional[str] = None
    units: Optional[str] = None
    set_value: Optional[Any] = None
    stop_time: Optional[str] = None
    cov_increment: Optional[float] = None
