# generated by datamodel-codegen:
#   filename:  config_blobset.json

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .common import Blobsets
from .config_blobset_blob import BlobBlobsetConfig


class BlobsetConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blobsets: Optional[Blobsets] = Field(
        None, description='Placeholder to create generated code enum'
    )
    blobs: Optional[
        Dict[constr(pattern=r'^_?[a-z][a-z0-9]*(_[a-z0-9]+)*$'), BlobBlobsetConfig]
    ] = None
