# generated by datamodel-codegen:
#   filename:  configuration_pubber.json

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field

from .configuration_endpoint import EndpointConfiguration
from .options_pubber import PubberOptions


class PubberConfiguration(BaseModel):
    """
    Parameters to define a pubber runtime instance
    """

    model_config = ConfigDict(
        extra='allow',
    )
    endpoint: Optional[EndpointConfiguration] = None
    iotProject: Optional[str] = Field(None, description='IoT Core ingest project id')
    projectId: Optional[str] = None
    registryId: Optional[str] = None
    deviceId: Optional[str] = None
    gatewayId: Optional[str] = None
    sitePath: Optional[str] = None
    keyFile: Optional[str] = 'local/rsa_private.pkcs8'
    algorithm: Optional[str] = 'RS256'
    serialNo: Optional[str] = None
    macAddr: Optional[str] = None
    keyBytes: Optional[Any] = None
    options: Optional[PubberOptions] = None
