# generated by datamodel-codegen:
#   filename:  config_mapping.json

from __future__ import annotations

from datetime import datetime
from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .config_mapping_device import DeviceMappingConfig


class MappingConfig(BaseModel):
    """
    Configuration for [mapping](../docs/specs/mapping.md)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='RFC 3339 timestamp the configuration was generated',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
    devices: Optional[Dict[constr(pattern=r''), DeviceMappingConfig]] = Field(
        None, description='Configuration of mapped devices'
    )
