# generated by datamodel-codegen:
#   filename:  config_discovery.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .common import Depth
from .config_discovery_family import FamilyDiscoveryConfig


@dataclass
class Enumerations(DataModel):
    """
    Enumeration depth for self-enumerations.
    """

    families: Optional[Depth] = None
    devices: Optional[Depth] = None
    points: Optional[Depth] = None
    features: Optional[Depth] = None


@dataclass
class DiscoveryConfig(DataModel):
    """
    Configuration for [discovery](../docs/specs/discovery.md)
    """

    generation: Optional[str] = None
    enumerations: Optional[Enumerations] = None
    families: Optional[Dict[str, FamilyDiscoveryConfig]] = None
