# generated by datamodel-codegen:
#   filename:  config_discovery_trace.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class TraceDiscoveryConfig(DataModel):
    """
    Configuration parameters for trace-level discovery operations (when depth is 'trace')
    """

    interface: Optional[str] = None
    filter: Optional[str] = None
    max_bytes: Optional[int] = None
