# generated by datamodel-codegen:
#   filename:  config_mapping_device.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .entry import Entry


@dataclass
class DeviceMappingConfig(DataModel):
    """
    Configuration for [mapping](../docs/specs/mapping.md)
    """

    guid: Optional[str] = None
    applied: Optional[str] = None
    requested: Optional[str] = None
    status: Optional[Entry] = None
