# generated by datamodel-codegen:
#   filename:  config_gateway.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .model_localnet_family import FamilyLocalnetModel


class GatewayConfig(BaseModel):
    """
    Configuration for gateways. Only required for devices which are acting as [gateways](../docs/specs/gateway.md)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    proxy_ids: Optional[List[constr(pattern=r'^[A-Z]{2,6}-[1-9][0-9]*$')]] = Field(
        None,
        description='An array of all the device IDs which are bound to the device',
        examples=[['AHU-22']],
    )
    target: Optional[FamilyLocalnetModel] = Field(
        None,
        description='For proxied devices, this represents the target proxy device address for use by its gateway',
    )
