# generated by datamodel-codegen:
#   filename:  config_localnet.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .config_localnet_family import FamilyLocalnetConfig


class LocalnetConfig(BaseModel):
    """
    Currently unused: request local network configuration
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    families: Optional[
        Dict[constr(pattern=r'^[a-z][a-z0-9]*(_[a-z0-9]+)*$'), FamilyLocalnetConfig]
    ] = Field(None, description='Address family config for reporting.')
