# generated by datamodel-codegen:
#   filename:  config_discovery_family.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from ._base import DataModel
from .common import Depth
from .config_discovery_trace import TraceDiscoveryConfig


@dataclass
class FamilyDiscoveryConfig(DataModel):
    """
    Configuration for [discovery](../docs/specs/discovery.md)
    """

    generation: Optional[str] = None
    scan_interval_sec: Optional[int] = None
    scan_duration_sec: Optional[int] = None
    addrs: Optional[List[str]] = None
    networks: Optional[List[str]] = None
    passive_sec: Optional[int] = None
    depth: Optional[Depth] = None
    trace: Optional[TraceDiscoveryConfig] = None
