# generated by datamodel-codegen:
#   filename:  config_mapping_device.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .entry import Entry


class DeviceMappingConfig(BaseModel):
    """
    Configuration for [mapping](../docs/specs/mapping.md)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    guid: Optional[str] = Field(None, description='Device guid')
    applied: Optional[datetime] = Field(
        None,
        description='Last time the mapping was successfully applied for this device',
    )
    requested: Optional[datetime] = Field(
        None, description='Timestamp of requested device model export'
    )
    status: Optional[Entry] = None
