# generated by datamodel-codegen:
#   filename:  config_alarmset.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .config_alarmset_alarm import AlarmAlarmsetConfig


@dataclass
class AlarmsetConfig(DataModel):
    """
    [Alarmset Config Documentation](../docs/messages/alarmset.md#config)
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    state_etag: Optional[str] = None
    set_value_expiry: Optional[str] = None
    sample_limit_sec: Optional[int] = None
    sample_rate_sec: Optional[int] = 300
    alarms: Optional[Dict[str, AlarmAlarmsetConfig]] = None
