# generated by datamodel-codegen:
#   filename:  config_alarmset_alarm.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class AlarmAlarmsetConfig(DataModel):
    ref: Optional[str] = None
