# generated by datamodel-codegen:
#   filename:  config.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .config_blobset import BlobsetConfig
from .config_discovery import DiscoveryConfig
from .config_gateway import GatewayConfig
from .config_localnet import LocalnetConfig
from .config_pointset import PointsetConfig
from .config_system import SystemConfig


class Config(BaseModel):
    """
    The config block controls a device's intended behavior. [Config Documentation](../docs/messages/config.md)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='RFC 3339 UTC timestamp the configuration was generated',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
    downgraded_from: Optional[str] = Field(
        None, description='Original version of schema pre-downgrade'
    )
    system: Optional[SystemConfig] = None
    gateway: Optional[GatewayConfig] = None
    discovery: Optional[DiscoveryConfig] = None
    localnet: Optional[LocalnetConfig] = None
    blobset: Optional[BlobsetConfig] = None
    pointset: Optional[PointsetConfig] = None
