# generated by datamodel-codegen:
#   filename:  config_localnet_family.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class FamilyLocalnetConfig(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )
