# generated by datamodel-codegen:
#   filename:  config_discovery_family.json

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, conint

from .common import Depth


class FamilyDiscoveryConfig(BaseModel):
    """
    Configuration for [discovery](../docs/specs/discovery.md)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    generation: Optional[datetime] = Field(
        None, description='Generational marker for controlling discovery'
    )
    scan_interval_sec: Optional[conint(ge=0)] = Field(
        None, description='Period, in seconds, for automatic scanning'
    )
    scan_duration_sec: Optional[conint(ge=0)] = Field(
        None, description='Scan duration, in seconds'
    )
    passive_sec: Optional[conint(ge=0)] = Field(
        None, description='Holdoff time for passively discovered devices'
    )
    depth: Optional[Depth] = Field(
        None, description='Indicates implicit enumeration of discovered devices'
    )
