# generated by datamodel-codegen:
#   filename:  config.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .config_blobset import BlobsetConfig
from .config_discovery import DiscoveryConfig
from .config_gateway import GatewayConfig
from .config_localnet import LocalnetConfig
from .config_pointset import PointsetConfig
from .config_system import SystemConfig


@dataclass
class Config(DataModel):
    """
    The config block controls a device's intended behavior. [Config Documentation](../docs/messages/config.md)
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    downgraded_from: Optional[str] = None
    system: Optional[SystemConfig] = None
    gateway: Optional[GatewayConfig] = None
    discovery: Optional[DiscoveryConfig] = None
    localnet: Optional[LocalnetConfig] = None
    blobset: Optional[BlobsetConfig] = None
    pointset: Optional[PointsetConfig] = None
