# generated by datamodel-codegen:
#   filename:  configuration_pod_bridge.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .configuration_endpoint import EndpointConfiguration


@dataclass
class BridgePodConfiguration(DataModel):
    """
    Parameters to define a bridge between message domains
    """

    enabled: Optional[str] = None
    from_: Optional[EndpointConfiguration] = None
    morf: Optional[EndpointConfiguration] = None
