# generated by datamodel-codegen:
#   filename:  config_alarmset.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .config_alarmset_alarm import AlarmAlarmsetConfig


@dataclass
class AlarmsetConfig(DataModel):
    """
    [Alarmset Config Documentation](../docs/messages/alarmset.md#config)
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    alarms: Optional[Dict[str, AlarmAlarmsetConfig]] = None
