# generated by datamodel-codegen:
#   filename:  config_udmi.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .state_udmi import Setup as Setup_1


@dataclass
class Setup(DataModel):
    hostname: Optional[str] = None
    functions_min: Optional[int] = None
    functions_max: Optional[int] = None
    udmi_version: Optional[str] = None
    udmi_commit: Optional[str] = None
    udmi_ref: Optional[str] = None
    udmi_timever: Optional[str] = None
    built_at: Optional[str] = None
    built_by: Optional[str] = None
    deployed_at: Optional[str] = None
    deployed_by: Optional[str] = None


@dataclass
class UdmiConfig(DataModel):
    """
    Config for a UDMI reflector client
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    last_state: Optional[str] = None
    reply: Optional[Setup_1] = None
    setup: Optional[Setup] = None
