# generated by datamodel-codegen:
#   filename:  config_mapping.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .config_mapping_device import DeviceMappingConfig


@dataclass
class MappingConfig(DataModel):
    """
    Configuration for [mapping](../docs/specs/mapping.md)
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    devices: Optional[Dict[str, DeviceMappingConfig]] = None
    extras_deletion_days: Optional[int] = None
    devices_deletion_days: Optional[int] = None
