# generated by datamodel-codegen:
#   filename:  config_blobset_blob.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .common import Phase


class BlobBlobsetConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    phase: Optional[Phase] = None
    url: Optional[str] = None
    sha256: Optional[constr(pattern=r'^[0-9a-f]{64}$')] = Field(
        None, description='Expected hash of the retrieved resource'
    )
    generation: Optional[datetime] = Field(
        None,
        description='RFC 3339 UTC timestamp of the blob generation',
        examples=['2019-01-17T14:02:29.364Z'],
    )
