# generated by datamodel-codegen:
#   filename:  data_template.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class MessageTemplateData:
    """
    Information container for simple template substitution.
    """

    timestamp: Optional[str] = None
