# generated by datamodel-codegen:
#   filename:  data_template.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class MessageTemplateData(DataModel):
    """
    Information container for simple template substitution.
    """

    timestamp: Optional[str] = None
