# generated by datamodel-codegen:
#   filename:  data_template.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class MessageTemplateData(BaseModel):
    """
    Information container for simple template substitution.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[str] = Field(None, description='Message timestamp')
