# generated by datamodel-codegen:
#   filename:  dimension.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class Dimension(DataModel):
    """
    Dimensions with a value and a unit
    """

    value: Optional[float] = None
    unit: Optional[str] = None
