# generated by datamodel-codegen:
#   filename:  dimension.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Optional, Union

from pydantic import BaseModel, ConfigDict, constr


class Dimension(BaseModel):
    """
    Dimensions with a value and a unit
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    value: Optional[float] = None
    unit: Optional[
        Union[
            constr(pattern=r'^m2$'),
            constr(pattern=r'^sqf$'),
            constr(pattern=r'^kgCO2e/kWh'),
            constr(pattern=r'^£/m3$'),
            constr(pattern=r'^\$/gal'),
            constr(pattern=r'^£/kWh$'),
            constr(pattern=r'^\$/kWh$'),
        ]
    ] = None
