# generated by datamodel-codegen:
#   filename:  discovery_family.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class FamilyDiscovery(DataModel):
    """
    Discovery information for a protocol family.
    """

    addr: Optional[str] = None
    ref: Optional[str] = None
