# generated by datamodel-codegen:
#   filename:  discovery_family.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, constr


class FamilyDiscovery(BaseModel):
    """
    Discovery information for a protocol family.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    addr: Optional[constr(pattern=r'^[-_.:0-9A-Z]+$')] = Field(
        None, description='Device addr in the namespace of the given family'
    )
