# generated by datamodel-codegen:
#   filename:  discovery_alarm_ref.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class AlarmRefDiscovery(DataModel):
    """
    Object representation for for a single alarm reference discovery
    """

    alarm: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    category: Optional[str] = None
    severity: Optional[str] = None
    requires_ack: Optional[bool] = None
    return_to_normal_event: Optional[bool] = None
    return_requires_ack: Optional[bool] = None
