# generated by datamodel-codegen:
#   filename:  discovery_feature.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from .common import Stage


@dataclass
class FeatureDiscovery:
    """
    Object representation for for a single feature
    """

    stage: Optional[Stage] = None
