# generated by datamodel-codegen:
#   filename:  download_blobset.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .configuration_endpoint import EndpointConfiguration


@dataclass
class BlobsetDownload(DataModel):
    """
    Direct cloud-to-device payload delivery for blobset configurations over the download/blobset channel.
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    blobs: Optional[Dict[str, EndpointConfiguration]] = None
