# generated by datamodel-codegen:
#   filename:  entry.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .category import Category


@dataclass
class Entry(DataModel):
    message: Optional[str] = None
    detail: Optional[str] = None
    category: Optional[Category] = None
    timestamp: Optional[str] = None
    level: Optional[int] = None
