# generated by datamodel-codegen:
#   filename:  envelope.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional

from ._base import DataModel


class SubFolder(Enum):
    udmi = 'udmi'
    update = 'update'
    invalid = 'invalid'
    error = 'error'
    cloud = 'cloud'
    discovery = 'discovery'
    mapping = 'mapping'
    system = 'system'
    gateway = 'gateway'
    swarm = 'swarm'
    localnet = 'localnet'
    pointset = 'pointset'
    validation = 'validation'
    blobset = 'blobset'
    monitoring = 'monitoring'


class SubType(Enum):
    invalid = 'invalid'
    local = 'local'
    reflect = 'reflect'
    events = 'events'
    errors = 'errors'
    commands = 'commands'
    config = 'config'
    state = 'state'
    query = 'query'
    reply = 'reply'
    model = 'model'


@dataclass
class Envelope(DataModel):
    """
    The UDMI `envelope` is not a message itself, per se, but the attributes and other information that is delivered along with a message. [Message Envelope Documentation](../docs/messages/envelope.md)
    """

    deviceId: Optional[str] = None
    deviceNumId: Optional[str] = None
    deviceRegistryId: Optional[str] = None
    deviceRegistryLocation: Optional[str] = None
    projectId: Optional[str] = None
    payload: Optional[str] = None
    source: Optional[str] = None
    gatewayId: Optional[str] = None
    transactionId: Optional[str] = None
    publishTime: Optional[str] = None
    rawFolder: Optional[str] = None
    subFolder: Optional[SubFolder] = None
    subType: Optional[SubType] = None
