# generated by datamodel-codegen:
#   filename:  equipment_translation.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Dict, Optional

from pydantic import Field, RootModel, constr

from .building_translation import BuildingTranslation


class BuildingConfig(
    RootModel[Optional[Dict[constr(pattern=r''), BuildingTranslation]]]
):
    root: Optional[Dict[constr(pattern=r''), BuildingTranslation]] = Field(
        None,
        description='[Discovery result](../docs/specs/discovery.md) with implicit results',
        title='Building Config',
    )
