# generated by datamodel-codegen:
#   filename:  equipment_translation.json

from __future__ import annotations

from typing import Dict, Optional

from .building_translation import BuildingTranslation

BuildingConfig = Optional[Dict[str, BuildingTranslation]]
