# generated by datamodel-codegen:
#   filename:  events_pointset.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .events_pointset_point import PointPointsetEvents


@dataclass
class PointsetEvents(DataModel):
    """
    A set of points reporting telemetry data. [Pointset Events Documentation](../docs/messages/pointset.md#telemetry)
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    upgraded_from: Optional[str] = None
    partial_update: Optional[bool] = None
    points: Optional[Dict[str, PointPointsetEvents]] = None
