# generated by datamodel-codegen:
#   filename:  events_pointset_point.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional


@dataclass
class PointPointsetEvents:
    """
    Object representation for for a single point
    """

    present_value: Optional[Any] = None
