# generated by datamodel-codegen:
#   filename:  events_alarmset.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .events_alarmset_alarm import AlarmAlarmsetEvents


@dataclass
class AlarmsetEvents(DataModel):
    """
    A set of alarms reporting telemetry data. [Alarmset Events Documentation](../docs/messages/alarmset.md#telemetry)
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    upgraded_from: Optional[str] = None
    partial_update: Optional[bool] = None
    alarms: Optional[Dict[str, AlarmAlarmsetEvents]] = None
