# generated by datamodel-codegen:
#   filename:  events_mapping_entities.json

from __future__ import annotations

from typing import Dict, Optional

from ._base import DataModel
from .events_mapping_entity import MappingEventEntity

MappingEventsEntities = Optional[Dict[str, MappingEventEntity]]
