# generated by datamodel-codegen:
#   filename:  events_mapping_entity.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Dict, List, Optional

from ._base import DataModel
from .equipment_translation import BuildingConfig
from .virtual_links import VirtualEquipmentLinks


class Connections(Enum):
    CONTAINS = 'CONTAINS'


@dataclass
class MappingEventEntity(DataModel):
    code: Optional[str] = None
    type: Optional[str] = None
    cloud_device_id: Optional[str] = None
    connections: Optional[Dict[str, Connections]] = None
    links: Optional[VirtualEquipmentLinks] = None
    translation: Optional[BuildingConfig] = None
    missing_telemetry_fields: Optional[List[str]] = None
