# generated by datamodel-codegen:
#   filename:  events_validation.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from ._base import DataModel
from .entry import Entry


@dataclass
class Pointset(DataModel):
    """
    Errors specific to pointset handling
    """

    missing: Optional[List[str]] = None
    extra: Optional[List[str]] = None


@dataclass
class ValidationEvents(DataModel):
    """
    Validation device result
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    sub_folder: Optional[str] = None
    sub_type: Optional[str] = None
    status: Optional[Entry] = None
    pointset: Optional[Pointset] = None
    errors: Optional[List[Entry]] = None
