# generated by datamodel-codegen:
#   filename:  events_mapping.json

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .entry import Entry
from .events_mapping_entities import MappingEventsEntities


class MappingEvents(BaseModel):
    """
    [Mapping result](../docs/specs/mapping.md) with implicit enumeration
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='RFC 3339 timestamp the configuration was generated',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
    status: Optional[Entry] = None
    entities: Optional[MappingEventsEntities] = None
