# generated by datamodel-codegen:
#   filename:  events_alarmset_alarm.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .alarm_ack import AlarmAcknowledgement


@dataclass
class AlarmAlarmsetEvents(DataModel):
    """
    Object representation for for a single alarm
    """

    activate_time: Optional[str] = None
    activate_ack: Optional[AlarmAcknowledgement] = None
    active: Optional[bool] = None
    return_to_normal_time: Optional[str] = None
    return_to_normal_ack: Optional[AlarmAcknowledgement] = None
