# generated by datamodel-codegen:
#   filename:  events_validation_device.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .entry import Entry


@dataclass
class DeviceValidationEvents(DataModel):
    """
    Validation summary information for an individual device.
    """

    last_seen: Optional[str] = None
    oldest_mark: Optional[str] = None
    status: Optional[Entry] = None
