# generated by datamodel-codegen:
#   filename:  events_alarmset.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .events_alarmset_alarm import AlarmAlarmsetEvents


@dataclass
class AlarmsetEvents(DataModel):
    """
    A set of alarm events.
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    upgraded_from: Optional[str] = None
    alarms: Optional[Dict[str, AlarmAlarmsetEvents]] = None
