# generated by datamodel-codegen:
#   filename:  events_udmi.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from ._base import DataModel
from .entry import Entry


@dataclass
class UdmiEvents(DataModel):
    """
    Used for udmi events such as logging.
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    logentries: Optional[List[Entry]] = None
