# generated by datamodel-codegen:
#   filename:  events_pointset.json

from __future__ import annotations

from datetime import datetime
from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .events_pointset_point import PointPointsetEvents


class PointsetEvents(BaseModel):
    """
    A set of points reporting telemetry data. [Pointset Events Documentation](../docs/messages/pointset.md#telemetry)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='RFC 3339 UTC timestamp the telemetry event was generated',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
    upgraded_from: Optional[str] = Field(
        None, description='Original version of schema pre-upgrade'
    )
    partial_update: Optional[bool] = Field(
        None,
        description='Indicates if this is a partial update (only some points may be included)',
    )
    points: Optional[
        Dict[constr(pattern=r'^[a-z][a-z0-9]*(_[a-z0-9]+)*$'), PointPointsetEvents]
    ] = Field(
        None,
        description='Collection of point names, defining the representative point set for this device.',
    )
