# generated by datamodel-codegen:
#   filename:  events_mapping_entities.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Dict, Optional

from pydantic import Field, RootModel, constr

from .events_mapping_entity import MappingEventEntity


class MappingEventsEntities(
    RootModel[Optional[Dict[constr(pattern=r'^[-0-9a-z]+$'), MappingEventEntity]]]
):
    root: Optional[Dict[constr(pattern=r'^[-0-9a-z]+$'), MappingEventEntity]] = Field(
        None,
        description='Mapper output describing a group of devices by their guids',
        title='Mapping Events Entities',
    )
