# generated by datamodel-codegen:
#   filename:  events_streams.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class StreamsEvents(DataModel):
    """
    Sequential data stream chunks for reliable transport over MQTT (e.g. PCAP traces, firmware blobs, reliable alarms, logs playback).
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    session_id: Optional[str] = None
    event_no: Optional[int] = None
    chunk_index: Optional[int] = None
    total_chunks: Optional[int] = None
    data: Optional[str] = None
