# generated by datamodel-codegen:
#   filename:  events_alarmset_alarm.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Union

from ._base import DataModel


@dataclass
class AlarmAlarmsetEvents(DataModel):
    """
    Object representation for for a single alarm
    """

    present_value: Optional[Union[str, bool, float]] = None
