# generated by datamodel-codegen:
#   filename:  events_mapping.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .entry import Entry
from .events_mapping_entities import MappingEventsEntities


@dataclass
class MappingEvents(DataModel):
    """
    [Mapping result](../docs/specs/mapping.md) with implicit enumeration
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    status: Optional[Entry] = None
    entities: Optional[MappingEventsEntities] = None
