# generated by datamodel-codegen:
#   filename:  events_discovery.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional

from ._base import DataModel
from .ancillary_properties import AncillaryProperties
from .discovery_family import FamilyDiscovery
from .discovery_feature import FeatureDiscovery
from .discovery_ref import RefDiscovery
from .entry import Entry
from .model_cloud import CloudModel
from .model_pointset_point import PointPointsetModel
from .state_system_hardware import StateSystemHardware


@dataclass
class System(DataModel):
    description: Optional[str] = None
    name: Optional[str] = None
    serial_no: Optional[str] = None
    ancillary: Optional[AncillaryProperties] = None
    hardware: Optional[StateSystemHardware] = None


@dataclass
class DiscoveryEvents(DataModel):
    """
    [Discovery result](../docs/specs/discovery.md) with implicit discovery
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    generation: Optional[str] = None
    status: Optional[Entry] = None
    family: Optional[Any] = None
    addr: Optional[str] = None
    network: Optional[str] = None
    event_no: Optional[int] = None
    families: Optional[Dict[str, FamilyDiscovery]] = None
    registries: Optional[Dict[str, CloudModel]] = None
    devices: Optional[Dict[str, CloudModel]] = None
    points: Optional[Dict[str, PointPointsetModel]] = None
    refs: Optional[Dict[str, RefDiscovery]] = None
    features: Optional[Dict[str, FeatureDiscovery]] = None
    cloud_model: Optional[CloudModel] = None
    system: Optional[System] = None
