# generated by datamodel-codegen:
#   filename:  events.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .events_discovery import DiscoveryEvents
from .events_pointset import PointsetEvents
from .events_system import SystemEvents


@dataclass
class Events(DataModel):
    """
    Container object for all event schemas, not directly used.
    """

    system: Optional[SystemEvents] = None
    pointset: Optional[PointsetEvents] = None
    discovery: Optional[DiscoveryEvents] = None
