# generated by datamodel-codegen:
#   filename:  events_system.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from ._base import DataModel
from .entry import Entry


@dataclass
class Metrics(DataModel):
    mem_total_mb: Optional[float] = None
    mem_free_mb: Optional[float] = None
    store_total_mb: Optional[float] = None
    store_free_mb: Optional[float] = None
    system_load: Optional[float] = None


@dataclass
class SystemEvents(DataModel):
    """
    Used for system events such as logging. [System Event Documentation](../docs/messages/system.md#event)
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    upgraded_from: Optional[str] = None
    last_config: Optional[str] = None
    logentries: Optional[List[Entry]] = None
    event_no: Optional[int] = None
    metrics: Optional[Metrics] = None
