# generated by datamodel-codegen:
#   filename:  metadata.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .common import Operation
from .events_discovery import DiscoveryEvents
from .model_cloud import CloudModel
from .model_discovery import DiscoveryModel
from .model_features import TestingModel as TestingModel_1
from .model_gateway import GatewayModel
from .model_localnet import LocalnetModel
from .model_pointset import PointsetModel
from .model_system import SystemModel
from .model_testing import TestingModel


@dataclass
class Metadata(DataModel):
    """
    [Metadata](../docs/specs/metadata.md) is a description about the device: a specification about how the device should be configured and expectations about what the device should be doing. Defined by `metadata.json`
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    upgraded_from: Optional[str] = None
    hash: Optional[str] = None
    operation: Optional[Operation] = None
    cloud: Optional[CloudModel] = None
    system: Optional[SystemModel] = None
    gateway: Optional[GatewayModel] = None
    discovery: Optional[DiscoveryModel] = None
    localnet: Optional[LocalnetModel] = None
    testing: Optional[TestingModel] = None
    features: Optional[TestingModel_1] = None
    pointset: Optional[PointsetModel] = None
    structure: Optional[Dict[str, DiscoveryEvents]] = None
