# generated by datamodel-codegen:
#   filename:  model_testing.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional

from ._base import DataModel
from .model_testing_ota import OtaTestingModel
from .model_testing_target import TargetTestingModel


@dataclass
class TestingModel(DataModel):
    """
    Testing target parameters
    """

    nostate: Optional[bool] = None
    targets: Optional[Dict[str, TargetTestingModel]] = None
    ota_targets: Optional[List[OtaTestingModel]] = None
