# generated by datamodel-codegen:
#   filename:  model_testing_target.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional

from ._base import DataModel


@dataclass
class TargetTestingModel(DataModel):
    target_point: Optional[str] = None
    target_value: Optional[Any] = None
