# generated by datamodel-codegen:
#   filename:  model_relationships.json

from __future__ import annotations

from typing import Dict, List, Optional

from ._base import DataModel
from .model_relationships_link import LinkRelationshipsModel

RelationshipsModel = Optional[Dict[str, List[LinkRelationshipsModel]]]
