# generated by datamodel-codegen:
#   filename:  model_relationships.json

from __future__ import annotations

from typing import Any, Dict, List, Optional, Union

from ._base import DataModel

EntityRelationships = Optional[Dict[str, Union[str, List[Any]]]]
