# generated by datamodel-codegen:
#   filename:  model_localnet_family.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class FamilyLocalnetModel(BaseModel):
    """
    The type of network
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    addr: Optional[str] = Field(
        None,
        description='The address of a device on the fieldbus/local network',
        examples=['0x414889'],
    )
    family: Optional[str] = None
