# generated by datamodel-codegen:
#   filename:  model_externals_link.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Union

from ._base import DataModel
from .virtual_links import VirtualEquipmentLinks


@dataclass
class LinkExternalsModel(DataModel):
    """
    Information about how this device links to a specific external model
    """

    ext_id: Optional[str] = None
    type: Optional[str] = None
    etag: Optional[str] = None
    label: Optional[str] = None
    connections: Optional[Dict[str, Union[str, List[Any]]]] = None
    links: Optional[VirtualEquipmentLinks] = None
