# generated by datamodel-codegen:
#   filename:  model_alarmset.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .model_alarmset_alarm import AlarmAlarmsetModel


@dataclass
class AlarmsetModel(DataModel):
    """
    Alarmset representing the abstract system expectation for what the device should be doing, and how it should be configured and operated. This block specifies the expected alarms that a device holds
    """

    alarms: Optional[Dict[str, AlarmAlarmsetModel]] = None
    exclude_units_from_config: Optional[bool] = None
    exclude_alarms_from_config: Optional[bool] = None
    sample_limit_sec: Optional[int] = None
    sample_rate_sec: Optional[int] = None
