# generated by datamodel-codegen:
#   filename:  model_testing.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from .model_testing_target import TargetTestingModel


@dataclass
class TestingModel:
    """
    Testing target parameters
    """

    nostate: Optional[bool] = None
    targets: Optional[Dict[str, TargetTestingModel]] = None
