# generated by datamodel-codegen:
#   filename:  model_testing_target.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional


@dataclass
class TargetTestingModel:
    target_point: Optional[str] = None
    target_value: Optional[Any] = None
