# generated by datamodel-codegen:
#   filename:  model_cloud_config.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class CloudConfigModel(DataModel):
    """
    Information specific to how the device communicates with the cloud.
    """

    static_file: Optional[str] = None
