# generated by datamodel-codegen:
#   filename:  model_policies.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from ._base import DataModel


@dataclass
class PoliciesModel(DataModel):
    """
    Device policies
    """

    named_policies: Optional[List[str]] = None
