# generated by datamodel-codegen:
#   filename:  model_discovery.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, constr

from .model_discovery_family import FamilyDiscoveryModel


class DiscoveryModel(BaseModel):
    """
    Discovery target parameters
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    families: Optional[
        Dict[constr(pattern=r'^[a-z][a-z0-9]*(_[a-z0-9]+)*$'), FamilyDiscoveryModel]
    ] = None
