# generated by datamodel-codegen:
#   filename:  model_relationships_detail.json

from __future__ import annotations

from dataclasses import dataclass

from ._base import DataModel


@dataclass
class DetailRelationshipsModel(DataModel):
    """
    Information for modeling noun-verb-noun relationships between devices
    """
