# generated by datamodel-codegen:
#   filename:  model_system.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from ._base import DataModel
from .model_system_hardware import SystemHardware

Tag = Optional[Any]


@dataclass
class Position(DataModel):
    x: Optional[float] = None
    y: Optional[float] = None
    z: Optional[float] = None


@dataclass
class Coordinates(DataModel):
    lat: Optional[float] = None
    long: Optional[float] = None
    alt_m: Optional[float] = None


@dataclass
class Location(DataModel):
    """
    Properties of the expected physical location of the device
    """

    site: Optional[str] = None
    panel: Optional[str] = None
    section: Optional[str] = None
    room: Optional[str] = None
    floor: Optional[str] = None
    floor_seq: Optional[int] = None
    position: Optional[Position] = None
    coordinates: Optional[Coordinates] = None


@dataclass
class Asset(DataModel):
    guid: Optional[str] = None
    site: Optional[str] = None
    name: Optional[str] = None


@dataclass
class PhysicalTag(DataModel):
    """
    Information used to print a physical QR code label.
    """

    asset: Optional[Asset] = None


@dataclass
class SystemModel(DataModel):
    """
    High-level system information about the device. [System Model Documentation](../docs/messages/system.md)
    """

    name: Optional[str] = None
    description: Optional[str] = None
    device_version: Optional[str] = None
    zone: Optional[str] = None
    node_type: Optional[str] = None
    tags: Optional[List[Tag]] = None
    location: Optional[Location] = None
    serial_no: Optional[str] = None
    hardware: Optional[SystemHardware] = None
    software: Optional[Dict[str, str]] = None
    physical_tag: Optional[PhysicalTag] = None
    adjunct: Optional[Dict[str, str]] = None
    min_loglevel: Optional[int] = 300
    metrics_rate_sec: Optional[int] = None
