# generated by datamodel-codegen:
#   filename:  model_system_hardware.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class SystemHardware(DataModel):
    """
    A collection of fields which describe the physical hardware of the device.
    """

    make: Optional[str] = None
    model: Optional[str] = None
    sku: Optional[str] = None
    rev: Optional[str] = None
