# generated by datamodel-codegen:
#   filename:  model_testing.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .model_testing_target import TargetTestingModel
from .model_testing_update import BlobUpdateTestingModel


@dataclass
class TestingModel(DataModel):
    """
    Testing target parameters
    """

    nostate: Optional[bool] = None
    targets: Optional[Dict[str, TargetTestingModel]] = None
    blob_update_targets: Optional[Dict[str, BlobUpdateTestingModel]] = None
