# generated by datamodel-codegen:
#   filename:  model_testing_target.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class TargetTestingModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    target_point: Optional[str] = Field(None, description='Point name used for testing')
    target_value: Optional[Any] = Field(None, description='Value used for testing')
