# generated by datamodel-codegen:
#   filename:  model_cloud_config.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class CloudConfigModel(BaseModel):
    """
    Information specific to how the device communicates with the cloud.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    static_file: Optional[str] = Field(
        None,
        description="Config file to use. Within the `config` directory in the device's metadata directory",
    )
