# generated by datamodel-codegen:
#   filename:  model_externals_link.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class LinkExternalsModel(DataModel):
    """
    Information about how this device links to a specific external model
    """

    ext_id: Optional[str] = None
    type: Optional[str] = None
    etag: Optional[str] = None
    label: Optional[str] = None
