# generated by datamodel-codegen:
#   filename:  model_pointset_point_links.json

from __future__ import annotations

from typing import Dict, Optional

from ._base import DataModel

PointsetPointLinks = Optional[Dict[str, str]]
