# generated by datamodel-codegen:
#   filename:  model_gateway.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .model_localnet_family import FamilyLocalnetModel


class GatewayModel(BaseModel):
    """
    [Gateway Documentation](../docs/specs/gateway.md)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    gateway_id: Optional[constr(pattern=r'^[A-Z]{2,6}-[1-9][0-9]*$')] = Field(
        None,
        description='The device ID of the gateway the device is bound to',
        examples=['GAT-100'],
    )
    target: Optional[FamilyLocalnetModel] = None
    proxy_ids: Optional[List[constr(pattern=r'^[A-Z]{2,6}-[1-9][0-9]*$')]] = Field(
        None,
        description='An array of all the device IDs which are bound to the device',
        examples=[['AHU-22']],
    )
