# generated by datamodel-codegen:
#   filename:  model_testing_ota.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional

from ._base import DataModel


class TestType(Enum):
    """
    Type of test to run for this payload. 'happy' expects successful application and version update. 'bad_hash' expects error state due to hash mismatch.
    """

    happy = 'happy'
    bad_hash = 'bad_hash'


@dataclass
class OtaTestingModel(DataModel):
    blob_key: Optional[str] = None
    url: Optional[str] = None
    sha256: Optional[str] = None
    version: Optional[str] = None
    test_type: Optional[TestType] = None
