# generated by datamodel-codegen:
#   filename:  model_policy.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from ._base import DataModel


@dataclass
class PolicyModel(DataModel):
    rule_sets: Optional[List[str]] = None
