# generated by datamodel-codegen:
#   filename:  model_localnet.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .model_localnet_family import FamilyLocalnetModel


@dataclass
class Parent(DataModel):
    """
    Parent device to which the device is physically connected
    """

    target: Optional[str] = None
    family: Optional[str] = None


@dataclass
class LocalnetModel(DataModel):
    """
    Used to describe device local network parameters
    """

    parent: Optional[Parent] = None
    families: Optional[Dict[str, FamilyLocalnetModel]] = None
