# generated by datamodel-codegen:
#   filename:  model_pointset.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .model_pointset_point import PointPointsetModel


@dataclass
class PointsetModel(DataModel):
    """
    Pointset representing the abstract system expectation for what the device should be doing, and how it should be configured and operated. This block specifies the expected points that a device holds
    """

    points: Optional[Dict[str, PointPointsetModel]] = None
    exclude_units_from_config: Optional[bool] = None
    exclude_points_from_config: Optional[bool] = None
    sample_limit_sec: Optional[int] = None
    sample_rate_sec: Optional[int] = None
