# generated by datamodel-codegen:
#   filename:  model_relationships_detail.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from ._base import DataModel

Tag = Optional[str]


@dataclass
class DetailRelationshipsModel(DataModel):
    """
    Information for modeling noun-verb-noun relationships between devices
    """

    tags: Optional[List[Tag]] = None
