# generated by datamodel-codegen:
#   filename:  model_localnet_family.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel


@dataclass
class FamilyLocalnetModel(DataModel):
    """
    The type of network
    """

    addr: Optional[str] = None
    network: Optional[str] = None
    adjunct: Optional[Dict[str, str]] = None
    shadow_id: Optional[str] = None
    parent_id: Optional[str] = None
    family: Optional[str] = None
