# generated by datamodel-codegen:
#   filename:  model_relationships_link.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class LinkRelationshipsModel(DataModel):
    """
    Information about how this device relates to another device
    """

    kind: Optional[str] = None
