# generated by datamodel-codegen:
#   filename:  model_testing_ota.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class OtaTestingModel(DataModel):
    blob_name: Optional[str] = None
    url: Optional[str] = None
    sha256: Optional[str] = None
    version: Optional[str] = None
