# generated by datamodel-codegen:
#   filename:  monitoring.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from .monitoring_metric import MonitoringMetric


class Monitoring(BaseModel):
    """
    Output from UDMIS monitoring
    """

    metric: Optional[MonitoringMetric] = None
