# generated by datamodel-codegen:
#   filename:  monitoring.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .monitoring_metric import MonitoringMetric


@dataclass
class Monitoring(DataModel):
    """
    Output from UDMIS monitoring
    """

    metric: Optional[MonitoringMetric] = None
