# generated by datamodel-codegen:
#   filename:  monitoring_metric.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict

from .envelope import Envelope
from .events_system import SystemEvents


class MonitoringMetric(BaseModel):
    """
    One metric
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    system: Optional[SystemEvents] = None
    envelope: Optional[Envelope] = None
