# generated by datamodel-codegen:
#   filename:  mosquitto_client_response.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from ._base import DataModel


@dataclass
class Role(DataModel):
    rolename: Optional[str] = None


@dataclass
class Client(DataModel):
    username: Optional[str] = None
    clientid: Optional[str] = None
    roles: Optional[List[Role]] = None


@dataclass
class Data(DataModel):
    client: Optional[Client] = None


@dataclass
class MosquittoClientResponse(DataModel):
    """
    Information returned by Mosquitto dynamic security getClient command.
    """

    command: Optional[str] = None
    error: Optional[str] = None
    status: Optional[int] = None
    data: Optional[Data] = None
