# generated by datamodel-codegen:
#   filename:  options_pubber.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class PubberOptions(DataModel):
    """
    Pubber runtime options
    """

    fixedSampleRate: Optional[int] = None
    noHardware: Optional[bool] = None
    noConfigAck: Optional[bool] = None
    noPersist: Optional[bool] = None
    noLastStart: Optional[bool] = None
    noLastConfig: Optional[bool] = None
    badCategory: Optional[bool] = None
    badVersion: Optional[bool] = None
    badAddr: Optional[bool] = None
    noProxy: Optional[bool] = None
    extraDevice: Optional[bool] = None
    barfConfig: Optional[bool] = None
    messageTrace: Optional[bool] = None
    extraPoint: Optional[str] = None
    configStateDelay: Optional[bool] = None
    missingPoint: Optional[str] = None
    extraField: Optional[str] = None
    emptyMissing: Optional[bool] = None
    redirectRegistry: Optional[str] = None
    msTimestamp: Optional[bool] = None
    smokeCheck: Optional[bool] = None
    skewClock: Optional[bool] = None
    noPointState: Optional[bool] = None
    noState: Optional[bool] = None
    noStatus: Optional[bool] = None
    noFolder: Optional[bool] = None
    badLevel: Optional[bool] = None
    spamState: Optional[bool] = None
    tweakState: Optional[bool] = None
    badState: Optional[bool] = None
    baseState: Optional[bool] = None
    dupeState: Optional[bool] = None
    noLog: Optional[bool] = None
    featureEnableSwap: Optional[bool] = None
    disableWriteback: Optional[bool] = None
    noWriteback: Optional[bool] = None
    fixedLogLevel: Optional[int] = None
    fastWrite: Optional[bool] = None
    delayWrite: Optional[bool] = None
    softwareFirmwareValue: Optional[str] = None
