# generated by datamodel-codegen:
#   filename:  persistent_device.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .configuration_endpoint import EndpointConfiguration


@dataclass
class DevicePersistent(DataModel):
    """
    Device persistent data
    """

    endpoint: Optional[EndpointConfiguration] = None
    restart_count: Optional[int] = None
