# generated by datamodel-codegen:
#   filename:  persistent_device.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict

from .configuration_endpoint import EndpointConfiguration


class DevicePersistent(BaseModel):
    """
    Device persistent data
    """

    model_config = ConfigDict(
        extra='allow',
    )
    endpoint: Optional[EndpointConfiguration] = None
    restart_count: Optional[int] = None
