# generated by datamodel-codegen:
#   filename:  properties.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional


class KeyType(Enum):
    RSA_PEM = 'RSA_PEM'
    RSA_X509_PEM = 'RSA_X509_PEM'


class Connect(Enum):
    direct = 'direct'


@dataclass
class Properties:
    key_type: Optional[KeyType] = None
    version: Optional[str] = None
    connect: Optional[Connect] = None
