# generated by datamodel-codegen:
#   filename:  query_cloud.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .common import Depth


class CloudQuery(BaseModel):
    """
    Information specific to how the device communicates with the cloud.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(None, examples=['2019-01-17T14:02:29.364Z'])
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
    generation: Optional[datetime] = Field(
        None,
        description='generational marker for this query',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    depth: Optional[Depth] = None
