# generated by datamodel-codegen:
#   filename:  query_cloud.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from .common import Depth


@dataclass
class CloudQuery:
    """
    Information specific to how the device communicates with the cloud.
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    generation: Optional[str] = None
    depth: Optional[Depth] = None
