# generated by datamodel-codegen:
#   filename:  site_metadata.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, List, Optional

from ._base import DataModel
from .dimension import Dimension

Tag = Optional[Any]


@dataclass
class Location(DataModel):
    address: Optional[str] = None
    lat: Optional[float] = None
    long: Optional[float] = None


@dataclass
class Links(DataModel):
    dashboard: Optional[str] = None
    docs: Optional[str] = None
    folder: Optional[str] = None
    image: Optional[str] = None
    repo: Optional[str] = None
    sheet: Optional[str] = None


@dataclass
class Area(DataModel):
    net_occupied_area: Optional[Dimension] = None
    gross_internal_area: Optional[Dimension] = None


@dataclass
class Electricity(DataModel):
    carbon_factor: Optional[Dimension] = None
    unit_cost: Optional[Dimension] = None


@dataclass
class Gas(Electricity):
    pass


@dataclass
class Water(DataModel):
    unit_cost: Optional[Dimension] = None


@dataclass
class Parameters(DataModel):
    area: Optional[Area] = None
    electricity: Optional[Electricity] = None
    gas: Optional[Gas] = None
    water: Optional[Water] = None


@dataclass
class SiteMetadata(DataModel):
    timestamp: Optional[str] = None
    version: Optional[str] = None
    site: Optional[str] = None
    name: Optional[str] = None
    tags: Optional[List[Tag]] = None
    strict_warnings: Optional[bool] = None
    location: Optional[Location] = None
    links: Optional[Links] = None
    parameters: Optional[Parameters] = None
