# generated by datamodel-codegen:
#   filename:  site_externals_link.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class LinkExternalsSite(DataModel):
    """
    Information about how this site links to a specific external model
    """

    description: Optional[str] = None
