# generated by datamodel-codegen:
#   filename:  state_localnet.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .state_localnet_family import FamilyLocalnetState


class LocalnetState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='Not included in messages published by devices. Part of message subblocks within cloud pipeline. RFC 3339 Timestamp the payload was generated',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
    families: Optional[
        Dict[constr(pattern=r'^_?[a-z][a-z0-9]*(_[a-z0-9]+)*$'), FamilyLocalnetState]
    ] = None
