# generated by datamodel-codegen:
#   filename:  state_pointset_point.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional

from ._base import DataModel
from .entry import Entry


class ValueState(Enum):
    """
    State of the individual point
    """

    initializing = 'initializing'
    applied = 'applied'
    updating = 'updating'
    overridden = 'overridden'
    invalid = 'invalid'
    failure = 'failure'


@dataclass
class PointPointsetState(DataModel):
    """
    Object representation for for a single point
    """

    units: Optional[str] = None
    value_state: Optional[ValueState] = None
    status: Optional[Entry] = None
