# generated by datamodel-codegen:
#   filename:  state_localnet_family.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict

from .entry import Entry


class FamilyLocalnetState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    addr: Optional[str] = None
    status: Optional[Entry] = None
