# generated by datamodel-codegen:
#   filename:  state.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .state_blobset import BlobsetState
from .state_discovery import DiscoveryState
from .state_gateway import GatewayState
from .state_localnet import LocalnetState
from .state_pointset import PointsetState
from .state_system import SystemState


class State(BaseModel):
    """
    [State](../docs/messages/state.md) message, defined by [`state.json`]
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='RFC 3339 UTC Timestamp the state payload was generated',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
    upgraded_from: Optional[str] = Field(
        None, description='Original version of schema pre-upgrade'
    )
    system: Optional[SystemState] = None
    gateway: Optional[GatewayState] = None
    discovery: Optional[DiscoveryState] = None
    localnet: Optional[LocalnetState] = None
    blobset: Optional[BlobsetState] = None
    pointset: Optional[PointsetState] = None
