# generated by datamodel-codegen:
#   filename:  state_alarmset_alarm.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .entry import Entry


@dataclass
class AlarmAlarmsetState(DataModel):
    """
    Object representation for for a single alarm
    """

    status: Optional[Entry] = None
