# generated by datamodel-codegen:
#   filename:  state_discovery.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .state_discovery_family import FamilyDiscoveryState


class DiscoveryState(BaseModel):
    """
    State for [discovery](../docs/specs/discovery.md)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='Not included in messages published by devices. Part of message subblocks within cloud pipeline. RFC 3339 Timestamp the payload was generated',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    version: Optional[str] = Field(
        None,
        description='Version of the UDMI schema, not included in messages published by devices',
    )
    generation: Optional[datetime] = Field(
        None, description='Generational marker to group results together'
    )
    families: Optional[
        Dict[constr(pattern=r'^[a-z][a-z0-9]*(_[a-z0-9]+)*$'), FamilyDiscoveryState]
    ] = Field(None, description='Discovery protocol families')
