# generated by datamodel-codegen:
#   filename:  state_validation_feature.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .state_validation_sequence import SequenceValidationState


@dataclass
class FeatureValidationState(DataModel):
    """
    Feature validation state
    """

    sequences: Optional[Dict[str, SequenceValidationState]] = None
