# generated by datamodel-codegen:
#   filename:  state_system_hardware.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class StateSystemHardware(BaseModel):
    """
    A collection of fields which describe the physical hardware of the device.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    make: Optional[str] = Field(
        None, description='The manufacturer of the device', examples=['Google']
    )
    model: Optional[str] = Field(
        None,
        description='The model of the device',
        examples=['Pixel 5', 'Pixel 6', 'Pixel 6 Pro'],
    )
    sku: Optional[str] = Field(
        None,
        description='A stock keeping unit which identifies the unique composition of a device, for example those with different hardware configurations',
        examples=['GF5KQ', '4215612'],
    )
    rev: Optional[str] = Field(
        None, description='Hardware revision of the device', examples=['A', 'B', '1']
    )
