# generated by datamodel-codegen:
#   filename:  state_alarmset.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .entry import Entry
from .state_alarmset_alarm import AlarmAlarmsetState


@dataclass
class AlarmsetState(DataModel):
    """
    A set of alarms reporting telemetry data.
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    state_etag: Optional[str] = None
    status: Optional[Entry] = None
    alarms: Optional[Dict[str, AlarmAlarmsetState]] = None
    upgraded_from: Optional[str] = None
