# generated by datamodel-codegen:
#   filename:  state_system_operation.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from .common import Mode


@dataclass
class StateSystemOperation:
    """
    A collection of state fields that describes the system operation
    """

    operational: Optional[bool] = None
    last_start: Optional[str] = None
    restart_count: Optional[int] = None
    mode: Optional[Mode] = None
