# generated by datamodel-codegen:
#   filename:  state_validation_schema.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, ConfigDict, constr

from .state_validation_sequence import SequenceValidationState


class SchemaValidationState(BaseModel):
    """
    Schema validation state
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    stages: Optional[Dict[constr(pattern=r'^[_a-z]+$'), Any]] = None
    sequences: Optional[Dict[constr(pattern=r'^[_a-z]+$'), SequenceValidationState]] = (
        None
    )
