# generated by datamodel-codegen:
#   filename:  state_validation_feature.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from .state_validation_sequence import SequenceValidationState


@dataclass
class FeatureValidationState:
    """
    Feature validation state
    """

    sequences: Optional[Dict[str, SequenceValidationState]] = None
