# generated by datamodel-codegen:
#   filename:  state_validation_capability.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional

from ._base import DataModel
from .common import Stage
from .entry import Entry


class Result(Enum):
    pass_ = 'pass'
    fail = 'fail'


@dataclass
class CapabilityValidationState(DataModel):
    """
    Capability validation state
    """

    summary: Optional[str] = None
    stage: Optional[Stage] = None
    result: Optional[Result] = None
    status: Optional[Entry] = None
    score: Optional[int] = None
    total: Optional[int] = None
