# generated by datamodel-codegen:
#   filename:  state_discovery_family.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional

from ._base import DataModel
from .entry import Entry


class Phase(Enum):
    """
    Current phase of an active discovery process
    """

    stopped = 'stopped'
    pending = 'pending'
    active = 'active'


@dataclass
class FamilyDiscoveryState(DataModel):
    """
    State for [discovery](../docs/specs/discovery.md)
    """

    generation: Optional[str] = None
    phase: Optional[Phase] = None
    active_count: Optional[int] = None
    passive_count: Optional[int] = None
    status: Optional[Entry] = None
