# generated by datamodel-codegen:
#   filename:  state_system.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from .entry import Entry
from .state_system_hardware import StateSystemHardware
from .state_system_operation import StateSystemOperation


@dataclass
class SystemState:
    """
    [System State Documentation](../docs/messages/system.md#state)
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    last_config: Optional[str] = None
    operation: Optional[StateSystemOperation] = None
    serial_no: Optional[str] = None
    hardware: Optional[StateSystemHardware] = None
    software: Optional[Dict[str, str]] = None
    params: Optional[Dict[str, str]] = None
    status: Optional[Entry] = None
    upgraded_from: Optional[str] = None
