# generated by datamodel-codegen:
#   filename:  state.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .state_blobset import BlobsetState
from .state_discovery import DiscoveryState
from .state_gateway import GatewayState
from .state_localnet import LocalnetState
from .state_pointset import PointsetState
from .state_system import SystemState


@dataclass
class State(DataModel):
    """
    [State](../docs/messages/state.md) message, defined by [`state.json`]
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    upgraded_from: Optional[str] = None
    system: Optional[SystemState] = None
    gateway: Optional[GatewayState] = None
    discovery: Optional[DiscoveryState] = None
    localnet: Optional[LocalnetState] = None
    blobset: Optional[BlobsetState] = None
    pointset: Optional[PointsetState] = None
