# generated by datamodel-codegen:
#   filename:  state_mapping.json

from __future__ import annotations

from datetime import datetime
from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, Field, constr

from .state_mapping_device import DeviceMappingState


class MappingState(BaseModel):
    """
    State for [mapping](../docs/specs/mapping.md)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='Not included in messages published by devices. Part of message subblocks within cloud pipeline. RFC 3339 Timestamp the payload was generated',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
    devices: Optional[Dict[constr(pattern=r''), DeviceMappingState]] = Field(
        None, description='Mapping state for all devices'
    )
