# generated by datamodel-codegen:
#   filename:  state_validation_feature.json

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, constr

from .state_validation_sequence import SequenceValidationState


class FeatureValidationState(BaseModel):
    """
    Feature validation state
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    sequences: Optional[Dict[constr(pattern=r'^[_a-z]+$'), SequenceValidationState]] = (
        None
    )
