# generated by datamodel-codegen:
#   filename:  state_mapping.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from ._base import DataModel
from .state_mapping_device import DeviceMappingState


@dataclass
class MappingState(DataModel):
    """
    State for [mapping](../docs/specs/mapping.md)
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    devices: Optional[Dict[str, DeviceMappingState]] = None
