# generated by datamodel-codegen:
#   filename:  state_mapping_device.json
#   timestamp: 2025-01-31T07:45:30+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .entry import Entry


class DeviceMappingState(BaseModel):
    """
    State for [mapping](../docs/specs/mapping.md)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    guid: Optional[str] = Field(None, description='Device guid')
    imported: Optional[datetime] = Field(
        None, description='Last time the mapping was imported'
    )
    discovered: Optional[datetime] = Field(
        None, description='Last received discovery message'
    )
    predicted: Optional[datetime] = Field(
        None, description='Last recommendation staging (result of automatic prediction)'
    )
    promoted: Optional[datetime] = Field(
        None, description='Last recommendation promotion (result of manual QA)'
    )
    exported: Optional[datetime] = Field(
        None, description='Last time this device mapping was exported'
    )
    status: Optional[Entry] = None
