# generated by datamodel-codegen:
#   filename:  state_localnet_family.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel
from .entry import Entry


@dataclass
class FamilyLocalnetState(DataModel):
    addr: Optional[str] = None
    status: Optional[Entry] = None
