# generated by datamodel-codegen:
#   filename:  state_mapping_device.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from .entry import Entry


@dataclass
class DeviceMappingState:
    """
    State for [mapping](../docs/specs/mapping.md)
    """

    guid: Optional[str] = None
    imported: Optional[str] = None
    discovered: Optional[str] = None
    predicted: Optional[str] = None
    promoted: Optional[str] = None
    exported: Optional[str] = None
    status: Optional[Entry] = None
