# generated by datamodel-codegen:
#   filename:  upload_discovery.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from ._base import DataModel


@dataclass
class DiscoveryUpload(DataModel):
    """
    Sequential binary chunk upload for discovery artifacts (e.g. PCAP traces) framed by config.discovery and state.discovery.
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    family: Optional[str] = None
    generation: Optional[str] = None
    session_id: Optional[str] = None
    event_no: Optional[int] = None
    chunk_index: Optional[int] = None
    total_chunks: Optional[int] = None
    sha256: Optional[str] = None
    data: Optional[str] = None
