# generated by datamodel-codegen:
#   filename:  virtual_links.json

from __future__ import annotations

from typing import Dict, Optional

from pydantic import Field, RootModel, constr


class VirtualEquipmentLinks(
    RootModel[
        Optional[
            Dict[
                constr(pattern=r'^[-0-9a-zA-Z$]+$'),
                Dict[constr(pattern=r'^[a-z_]+$'), constr(pattern=r'^[a-z0-9_]+$')],
            ]
        ]
    ]
):
    root: Optional[
        Dict[
            constr(pattern=r'^[-0-9a-zA-Z$]+$'),
            Dict[constr(pattern=r'^[a-z_]+$'), constr(pattern=r'^[a-z0-9_]+$')],
        ]
    ] = Field(
        None,
        description='Virtual equipment mapping, keyed by guid',
        title='Virtual Equipment Links',
    )
