cache:
  key: web-${CI_COMMIT_REF_SLUG}
  paths:
    - udmd/web/node_modules/
    - udmd/web/dist/

include:
  - project: 'buildings-iot/templates/cicd_pipelines'
    ref: main
    file: node.yml

stages:
  - build
  - test
  - static-scan
  - publish-docker

build-node:
  script:
    - npm install
    - npm install -g @angular/cli
    - npm run build

sonarqube-scan:
  rules:
    - when: never

scan-docker:
  rules:
    - when: never
    
publish-docker:
  variables: 
    VERSION: $CI_PIPELINE_IID
    DOCKER_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/udmd-web
    
test-node:
  stage: test
  rules:
    - when: never

