cache:
  key: web-${CI_COMMIT_REF_SLUG}
  paths:
    - udmd/web/node_modules/

include:
  - project: 'buildings-iot/templates/cicd_pipelines'
    ref: main
    file: node.yml

stages:
  - build
  - test
  - static-scan
  - publish-docker

sonarqube-scan:
  rules:
    - when: never

scan-docker:
  rules:
    - when: never

publish-docker:
  rules:
    - when: never

