"""
Sample: Zero-Config Connection (Auto-Detected mTLS)

This script demonstrates the "Smart Factory" capabilities of the UDMI library.
It provides the absolute minimum configuration (Device ID + Host).

The library automatically:
1.  Detects that no explicit Auth Provider (Basic/JWT) was given.
2.  Infers that **mTLS** is the intended security mechanism.
3.  Checks for keys/certs in the current directory (defaulting to `rsa_private.pem`).
4.  **GENERATES** them automatically if they are missing (Just-in-Time provisioning).
5.  Connects to the broker using these credentials.

PREREQUISITE:
If connecting to a local broker (Mosquitto), it must be configured to trust
the self-signed certificate generated by this script (`rsa_private.crt`),
OR be configured to accept the connection regardless.
"""

import logging
import os
import sys

from udmi.core.factory import create_device
from udmi.schema import EndpointConfiguration

DEVICE_ID = "AHU-1"
MQTT_HOSTNAME = "localhost"
MQTT_PORT = 8883
TOPIC_PREFIX = "/r/ZZ-TRI-FECTA/d/"

# Sample Client ID format for a local registry
CLIENT_ID = f"projects/local-project/locations/us-central1/registries/ZZ-TRI-FECTA/devices/{DEVICE_ID}"

# Default filename used by the library when none is specified
DEFAULT_KEY_FILE = "rsa_private.pem"
DEFAULT_CERT_FILE = "rsa_private.crt"

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG,
                        format='%(asctime)s - %(levelname)s - %(message)s')
    logger = logging.getLogger("SimpleConnect")

    try:
        # Define minimal configuration - We do NOT specify 'auth_provider'.
        endpoint = EndpointConfiguration(
            client_id=CLIENT_ID,
            hostname=MQTT_HOSTNAME,
            port=MQTT_PORT,
            topic_prefix=TOPIC_PREFIX,
        )

        logger.info("Initializing device with implicit configuration...")

        # Create Device using the Factory
        # We pass 'key_file' so the library knows where to save/load the auto-generated key.
        # If we omitted this, it might default to looking for 'rsa_private.pem' anyway,
        # but being explicit is safer for the sample.
        device = create_device(endpoint, key_file=DEFAULT_KEY_FILE)

        # Check if keys were generated
        if os.path.exists(DEFAULT_KEY_FILE):
            logger.info(f"Identity Verified:")
            logger.info(f"  Key:  {os.path.abspath(DEFAULT_KEY_FILE)}")
            if os.path.exists(DEFAULT_CERT_FILE):
                logger.info(f"  Cert: {os.path.abspath(DEFAULT_CERT_FILE)}")
                logger.info("  (Ensure your broker trusts this certificate)")

        logger.info("Starting device loop...")
        device.run()

    except KeyboardInterrupt:
        logger.info("Stopped by user.")
    except Exception as e:
        logger.critical(f"Fatal error: {e}", exc_info=True)
        sys.exit(1)
