[tool.poetry]
name = "udmi_schema"
version = "0.1.0"
description = "Generated UDMI schema classes"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
pydantic = "^2.10.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
