include:
  - project: 'buildings-iot/templates/cicd_pipelines'
    ref: main
    file: terraform/base.yml

stages:
  - init
  - validate
  - build
  - deploy
  - cleanup

cache:
  key: ${CI_PROJECT_NAME}-gcp
  paths:
    - ${TF_ROOT}/.terraform
    
variables:
  TF_ROOT: ${CI_PROJECT_DIR}/cloud/gcp
before_script:
  - cd cloud/gcp
  - sed -E < main.tf.template > main.tf -e "s/@GCP_PROJECT_ID@/${GCP_PROJECT_ID}/"
  - sed -E < udmi-sites.tf.template > udmi-sites.tf -e "s/@UDMI_SITE_NAME@/${UDMI_SITE_NAME}/" -e "s/@UDMI_SITE_REGION@/${UDMI_SITE_REGION}/" -e "s/@UDMI_SITE_GROUP@/${UDMI_SITE_GROUP}/"
  - echo "$GCP_CREDENTIALS" >> auth/credentials.json

init-staging:
  extends: .init
  environment: staging

init-lab:
  extends: .init
  environment: lab
  

validate-staging:
  extends: .validate
  environment: staging
  needs: ["init-staging"]

validate-lab:
  extends: .validate
  environment: lab
  needs: ["init-lab"]

build-staging:
  extends: .build
  environment: staging
  needs: ["validate-staging"]
  
build-lab:
  extends: .build
  environment: lab
  needs: ["validate-lab"]

deploy-staging:
  extends: .deploy
  environment: staging
  dependencies:
    - build-staging
  needs: ["build-staging"]

deploy-lab:
  extends: .deploy
  environment: lab
  dependencies:
    - build-lab
  needs: ["build-lab"]

destroy-staging:
  extends: .destroy
  environment: staging
  rules:
    - when: never

destroy-lab:
  extends: .destroy
  environment: lab
  rules:
    - when: never


