#!/bin/bash -e

ROOT=$(dirname $0)/..
cd $ROOT

messages=undefined
publisher="venv/bin/python testing/publisher.py bos-daq-testing"

if [ ! -d venv ]; then
    echo Run testing/install to setup python venv.
    false
fi

if [ -n "$1" ]; then
    messages=$1
    shift
fi

if [ -n "$1" ]; then
    echo $0 [messages_dir]
    false
fi

message_dir=testing/sequences/$messages

if [ ! -d $message_dir ]; then
    echo Message directory $message_dir not found.
    false
fi

export PUBSUB_EMULATOR_HOST=localhost:8085
for file in $message_dir/*.json; do
    echo Publishing $file
    filename=${file##*/}
    sequence=${filename%%_*}
    suffix=${filename#*_}
    target=${suffix%.json}
    topic=${target%%_*}
    subpre=${target#${topic}}
    subescape=${subpre#_}
    subfolder=$(tr _ / <<< $subescape)
    sed -e s:@subfolder@:$subfolder: testing/attributes.json > .attributes.json
    $publisher udmi_$topic .attributes.json $file
done
