#!/bin/bash -e

ROOT=$(dirname $0)/..
cd $ROOT

# Example of how to push image to container registry:
#   docker tag daqf/dts:latest us.gcr.io/dts-scale-testing/dts:1c6e1a409088
#   docker push us.gcr.io/dts-scale-testing/dts:1c6e1a409088
# edit deployment.yaml and update image id (1c6e1a409088)

kubectl apply -k dts
