# generated by datamodel-codegen:
#   filename:  ancillary_properties.json

from __future__ import annotations

from pydantic import BaseModel


class AncillaryProperties(BaseModel):
    """
    Arbitrary blob of json associated with this point
    """
