# generated by datamodel-codegen:
#   filename:  commands_discovery.json

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class DiscoveryCommand(BaseModel):
    """
    [Discovery command](../docs/specs/discovery.md) for provisioning
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='RFC 3339 UTC timestamp discovery telemetry event was generated',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
