# generated by datamodel-codegen:
#   filename:  configuration_pod_base.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class BasePodConfiguration(BaseModel):
    """
    Parameters to define pod base parameters
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    udmi_prefix: Optional[str] = Field(None, description='prefix for udmi namespacing')
    failure_rate: Optional[float] = Field(
        None, description='chance of random failure in various bits of the system'
    )
