# generated by datamodel-codegen:
#   filename:  config_localnet_family.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class FamilyLocalnetConfig(BaseModel):
    pass
    model_config = ConfigDict(
        extra='forbid',
    )
