# generated by datamodel-codegen:
#   filename:  discovery_feature.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict

from .common import Stage


class FeatureDiscovery(BaseModel):
    """
    Object representation for for a single feature
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    stage: Optional[Stage] = None
