# generated by datamodel-codegen:
#   filename:  events_system.json

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field

from .entry import Entry


class Metrics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mem_total_mb: Optional[float] = None
    mem_free_mb: Optional[float] = None
    store_total_mb: Optional[float] = None
    store_free_mb: Optional[float] = None
    system_load: Optional[float] = None


class SystemEvents(BaseModel):
    """
    Used for system events such as logging. [System Event Documentation](../docs/messages/system.md#event)
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='RFC 3339 UTC timestamp the event payload was generated',
        examples=['2019-01-17T14:02:29.364Z'],
    )
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
    upgraded_from: Optional[str] = Field(
        None, description='Original version of schema pre-upgrade'
    )
    last_config: Optional[datetime] = Field(
        None, description='Last config received', examples=['2019-01-17T14:02:29.364Z']
    )
    logentries: Optional[List[Entry]] = None
    event_no: Optional[int] = Field(None, description='Sequence number for this event')
    metrics: Optional[Metrics] = None
