# generated by datamodel-codegen:
#   filename:  events.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict

from .events_discovery import DiscoveryEvents
from .events_pointset import PointsetEvents
from .events_system import SystemEvents


class Events(BaseModel):
    """
    Container object for all event schemas, not directly used.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    system: Optional[SystemEvents] = None
    pointset: Optional[PointsetEvents] = None
    discovery: Optional[DiscoveryEvents] = None
