# generated by datamodel-codegen:
#   filename:  model_discovery_family.json

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, conint


class FamilyDiscoveryModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    generation: Optional[datetime] = Field(
        None,
        description='Generational marker for controlling discovery',
        examples=['2018-08-26T21:00:13Z'],
    )
    scan_interval_sec: Optional[conint(ge=0)] = Field(
        None, description='Period, in seconds, for automatic scanning'
    )
    scan_duration_sec: Optional[conint(ge=0)] = Field(
        None, description='Scan duration, in seconds'
    )
