# generated by datamodel-codegen:
#   filename:  model_testing.json

from __future__ import annotations

from typing import Dict, Optional

from pydantic import BaseModel, ConfigDict, constr

from .model_testing_target import TargetTestingModel


class TestingModel(BaseModel):
    """
    Testing target parameters
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    nostate: Optional[bool] = None
    targets: Optional[
        Dict[constr(pattern=r'^[a-z][a-z0-9]*(_[a-z0-9]+)*$'), TargetTestingModel]
    ] = None
