# generated by datamodel-codegen:
#   filename:  monitoring.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel

from .monitoring_metric import MonitoringMetric


class Monitoring(BaseModel):
    """
    Output from UDMIS monitoring
    """

    metric: Optional[MonitoringMetric] = None
