# generated by datamodel-codegen:
#   filename:  options_pubber.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class PubberOptions(BaseModel):
    """
    Pubber runtime options
    """

    model_config = ConfigDict(
        extra='allow',
    )
    fixedSampleRate: Optional[int] = None
    noHardware: Optional[bool] = None
    noConfigAck: Optional[bool] = None
    noPersist: Optional[bool] = None
    noLastStart: Optional[bool] = None
    noLastConfig: Optional[bool] = None
    badCategory: Optional[bool] = None
    badVersion: Optional[bool] = None
    badAddr: Optional[bool] = None
    noProxy: Optional[bool] = None
    extraDevice: Optional[bool] = None
    barfConfig: Optional[bool] = None
    messageTrace: Optional[bool] = None
    extraPoint: Optional[str] = None
    configStateDelay: Optional[bool] = None
    missingPoint: Optional[str] = None
    extraField: Optional[str] = None
    emptyMissing: Optional[bool] = None
    redirectRegistry: Optional[str] = None
    smokeCheck: Optional[bool] = None
    skewClock: Optional[bool] = None
    noPointState: Optional[bool] = None
    noState: Optional[bool] = None
    noStatus: Optional[bool] = None
    noFolder: Optional[bool] = None
    badLevel: Optional[bool] = None
    spamState: Optional[bool] = None
    tweakState: Optional[bool] = None
    badState: Optional[bool] = None
    baseState: Optional[bool] = None
    dupeState: Optional[bool] = None
    noLog: Optional[bool] = None
    featureEnableSwap: Optional[bool] = None
    disableWriteback: Optional[bool] = Field(
        None,
        description='Disable writeback, equivelant to marking all points as unwriteable',
    )
    noWriteback: Optional[bool] = Field(
        None,
        description='Removes writeback functionality, mimicking a device without Writeback support',
    )
    fixedLogLevel: Optional[int] = None
    softwareFirmwareValue: Optional[str] = None
