# generated by datamodel-codegen:
#   filename:  properties.json

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class KeyType(Enum):
    RSA_PEM = 'RSA_PEM'
    RSA_X509_PEM = 'RSA_X509_PEM'


class Connect(Enum):
    direct = 'direct'


class Properties(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    key_type: Optional[KeyType] = None
    version: Optional[str] = Field(None, description='Version of the UDMI schema')
    connect: Optional[Connect] = None
