# generated by datamodel-codegen:
#   filename:  state_system_operation.json

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .common import Mode


class StateSystemOperation(BaseModel):
    """
    A collection of state fields that describes the system operation
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    operational: Optional[bool] = Field(
        None, description='Operational status of the device.'
    )
    last_start: Optional[datetime] = Field(
        None, description='Last time the system started up.'
    )
    restart_count: Optional[int] = Field(None, description='Number of system restarts')
    mode: Optional[Mode] = None
