# generated by datamodel-codegen:
#   filename:  state_blobset_blob.json

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from .common import Phase
from .entry import Entry


class BlobBlobsetState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    phase: Optional[Phase] = None
    status: Optional[Entry] = None
    generation: Optional[datetime] = Field(
        None,
        description='The timestamp of the blob generation',
        examples=['2019-01-17T14:02:29.364Z'],
    )
