apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy2
  name: proxy2
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: proxy2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: proxy2
    spec:
      containers:
      - image: gcr.io/@GCP_PROJECT_ID@/mqttproxy@sha256:b854f4ab4e36df1a99e91253ae95c43b16c16135d0221ae7af91e7ceb9619a80
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: mqttproxy-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: ksa-haproxy
      terminationGracePeriodSeconds: 30