cache:
  key: api-${CI_COMMIT_REF_SLUG}
  paths:
    - udmd/api/node_modules/

include:
  - project: 'buildings-iot/templates/cicd_pipelines'
    ref: main
    file: node.yml

stages:
  - build
  - test
  - static-scan
  - publish-docker
  - deploy-staging

sonarqube-scan:
  rules:
    - when: never

scan-docker:
  rules:
    - when: never
    
publish-docker:
  variables: 
    VERSION: $CI_PIPELINE_IID
    DOCKER_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/udmd-api

deploy-staging:
  extends: .gks-deploy
  stage: deploy-staging
  environment: staging
  variables:
    CHART_NAME: udmi-api
    HELM_REPO: udmd/helm
    CHART_VALUES: --set image.tag=$CI_PIPELINE_IID --set gitlab.accessToken=$GITLAB_REGISTRY_TOKEN




    
    

