FROM alpine:latest

WORKDIR /root

RUN apk add --no-cache bash openjdk17 gcompat curl jq sudo git python3 moreutils mosquitto mosquitto-clients openssl coreutils

ADD build/libs pubber/build/libs/

ADD bin/ pubber/bin/

ADD build/udmi_etc/ etc/

ADD build/udmi_bin/ bin/

CMD ["/root/pubber/bin/run"]
