# generated by datamodel-codegen:
#   filename:  building_translation.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional


@dataclass
class BuildingTranslation:
    """
    [Discovery result](../docs/specs/discovery.md) with implicit enumeration
    """

    present_value: Optional[str] = None
    units: Optional[Any] = None
    states: Optional[Any] = None
