# generated by datamodel-codegen:
#   filename:  config_system_testing.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class TestingSystemConfig:
    """
    Configuration parameters for device-under-test
    """

    sequence_name: Optional[str] = None
    transaction_id: Optional[str] = None
    config_base: Optional[int] = None
    endpoint_type: Optional[str] = None
