# generated by datamodel-codegen:
#   filename:  config_localnet.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional

from .config_localnet_family import FamilyLocalnetConfig


@dataclass
class LocalnetConfig:
    """
    Currently unused: request local network configuration
    """

    families: Optional[Dict[str, FamilyLocalnetConfig]] = None
