# generated by datamodel-codegen:
#   filename:  config_discovery_family.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from .common import Depth


@dataclass
class FamilyDiscoveryConfig:
    """
    Configuration for [discovery](../docs/specs/discovery.md)
    """

    generation: Optional[str] = None
    scan_interval_sec: Optional[int] = None
    scan_duration_sec: Optional[int] = None
    passive_sec: Optional[int] = None
    depth: Optional[Depth] = None
