# generated by datamodel-codegen:
#   filename:  dimension.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class Dimension:
    """
    Dimensions with a value and a unit
    """

    value: Optional[float] = None
    unit: Optional[str] = None
