# generated by datamodel-codegen:
#   filename:  discovery_family.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class FamilyDiscovery:
    """
    Discovery information for a protocol family.
    """

    addr: Optional[str] = None
