# generated by datamodel-codegen:
#   filename:  discovery_ref.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional

from .ancillary_properties import AncillaryProperties
from .entry import Entry


@dataclass
class RefDiscovery:
    """
    Object representation for for a single point reference discovery
    """

    point: Optional[str] = None
    name: Optional[str] = None
    possible_values: Optional[List[str]] = None
    units: Optional[str] = None
    type: Optional[str] = None
    writable: Optional[bool] = None
    description: Optional[str] = None
    status: Optional[Entry] = None
    ancillary: Optional[AncillaryProperties] = None
