# generated by datamodel-codegen:
#   filename:  model_discovery_family.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class FamilyDiscoveryModel:
    generation: Optional[str] = None
    scan_interval_sec: Optional[int] = None
    scan_duration_sec: Optional[int] = None
