# generated by datamodel-codegen:
#   filename:  model_localnet_family.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class FamilyLocalnetModel:
    """
    The type of network
    """

    addr: Optional[str] = None
    family: Optional[str] = None
