# generated by datamodel-codegen:
#   filename:  monitoring.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from .monitoring_metric import MonitoringMetric


@dataclass
class Monitoring:
    """
    Output from UDMIS monitoring
    """

    metric: Optional[MonitoringMetric] = None
