# generated by datamodel-codegen:
#   filename:  monitoring_metric.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from .envelope import Envelope
from .events_system import SystemEvents


@dataclass
class MonitoringMetric:
    """
    One metric
    """

    system: Optional[SystemEvents] = None
    envelope: Optional[Envelope] = None
