# generated by datamodel-codegen:
#   filename:  state_udmi.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional


@dataclass
class Setup:
    user: Optional[str] = None
    udmi_version: Optional[str] = None
    functions_ver: Optional[int] = None
    udmi_commit: Optional[str] = None
    udmi_ref: Optional[str] = None
    udmi_timever: Optional[str] = None
    msg_source: Optional[str] = None
    update_to: Optional[str] = None
    tool_name: Optional[str] = None
    transaction_id: Optional[str] = None


@dataclass
class UdmiState:
    """
    State of a UDMI reflector client
    """

    timestamp: Optional[str] = None
    version: Optional[str] = None
    source: Optional[str] = None
    regions: Optional[Dict[str, str]] = None
    setup: Optional[Setup] = None
