# generated by datamodel-codegen:
#   filename:  state_blobset_blob.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

from .common import Phase
from .entry import Entry


@dataclass
class BlobBlobsetState:
    phase: Optional[Phase] = None
    status: Optional[Entry] = None
    generation: Optional[str] = None
