{
 "title": "Bridgehead",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container Name",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n    bucket: \"home\",\r\n    tag: \"container_name\",\r\n    predicate: (r) => r._measurement == \"docker_container_cpu\" \r\n        and r[\"com.docker.compose.project\"] == \"bridgehead\"\r\n)"
   }
  ]
 },
 "panels": [
  { "title": "Docker ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_ns\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"bridgehead\")\r\n  |> filter(fn: (r) => r.container_name =~ /^${container}$/)  \r\n  |> group(columns: [\"container_name\"])\r\n  |> last() \r\n  |> map(fn: (r) => ({\r\n      r with \r\n      uptime_seconds: float(v: r._value) / float(v: 1000000000)\r\n    })\r\n  )\r\n  |> map(fn: (r) => ({\r\n    r with \r\n    uptime_seconds: if r.container_status == \"exited\" then 0.0 else r.uptime_seconds\r\n  }))\r\n  |> keep(columns: [\"container_name\", \"uptime_seconds\"])\r\n  |> group(columns: [])\r\n  |> yield(name: \"current_uptime\")"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"bridgehead\")\r\n  |> filter(fn: (r) => r.container_name =~ /^${container}$/)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"container_name\", \"_value\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"docker_container_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_percent\")\r\n  |> filter(fn: (r) => r[\"com.docker.compose.project\"] == \"bridgehead\")\r\n  |> filter(fn: (r) => r.container_name =~ /^${container}$/)\r\n  |> group(columns: [\"container_name\"])\r\n  |> last()\r\n  |> keep(columns: [\"_time\", \"container_name\", \"_value\"])"
    }
   ]
  },
  { "title": "Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"device_validation\")\r\n  |> filter(fn: (r) => r._field == \"last_seen\" or r._field == \"status_message\")\r\n  |> group(columns: [\"device_name\", \"_field\"])\r\n  |> last()\r\n  |> group(columns: [\"device_name\"])\r\n  |> pivot(\r\n      rowKey: [\"device_name\"],\r\n      columnKey: [\"_field\"],\r\n      valueColumn: \"_value\"\r\n  )\r\n  |> keep(columns: [\"device_name\", \"last_seen\", \"status_message\"])\r\n  |> group(columns: [])\r\n  |> limit(n: 100)"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"validation_report\")\r\n  |> last()\r\n  |> pivot(\r\n        rowKey: [\"_time\", \"_measurement\"], \r\n        columnKey: [\"_field\"],            \r\n        valueColumn: \"_value\"             \r\n    )\r\n  |> drop(columns: [\"_start\", \"_stop\", \"host\"])"
    }
   ]
  },
  {
   "title": "Last Registrar Run Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"file\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"registrar_run_timestamp\")\r\n  |> last()\r\n  |> group(columns:[])\r\n  |> keep(columns:[\"_value\"])"
    }
   ]
  },
  { "title": "MQTT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Clients Connected",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"$SYS/broker/clients/connected\")\r\n  |> group(columns: [\"_measurement\", \"topic\"]) \r\n  |> aggregateWindow(\r\n      every: v.windowPeriod, \r\n      fn: last,\r\n      column: \"_value\",\r\n      createEmpty: true\r\n  )\r\n  |> fill(usePrevious: true)   \r\n  |> group(columns: [])\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Subscription Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\r\n  |> filter(fn: (r) => r[\"topic\"] == \"$SYS/broker/subscriptions/count\")\r\n  |> group(columns: [\"_measurement\", \"topic\"]) \r\n  |> aggregateWindow(\r\n      every: v.windowPeriod, \r\n      fn: last,\r\n      column: \"_value\",\r\n      createEmpty: true\r\n  )\r\n  |> fill(usePrevious: true)   \r\n  |> group(columns: [])\r\n  |> keep(columns: [\"_time\", \"_value\"])"
    }
   ]
  }
 ]
}