"""
Sample: Zero-Config mTLS with Auto-Generated Keys

This script demonstrates the Factory and Key Generation capabilities.

We provide an EndpointConfiguration WITHOUT an auth_provider.
The library will:
1. Infer that mTLS is required.
2. Check for default keys ('rsa_private.pem', 'client_cert.pem').
3. GENERATE them automatically if they are missing.
4. Use them to connect.

NOTE: For this to work with a local broker (like Mosquitto), you must
configure the broker to trust the self-signed cert generated by this script,
"""

import logging
import sys

from udmi.core.factory import ClientConfig
from udmi.core.factory import create_device
from udmi.core.messaging import TlsConfig
from udmi.schema import EndpointConfiguration

# --- Configuration ---
DEVICE_ID = "AHU-AUTO-1"
MQTT_HOSTNAME = "localhost"
MQTT_PORT = 8883
CA_CERT_FILE = "/path/to/ca.crt"

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')

    try:
        # 1. Define Endpoint Config (No Auth Provider specified!)
        endpoint = EndpointConfiguration.from_dict({
            "client_id": f"projects/local/locations/region/registries/reg/devices/{DEVICE_ID}",
            "hostname": MQTT_HOSTNAME,
            "port": MQTT_PORT,
            # "auth_provider": ...  <-- OMITTED intentonally
        })

        logging.info("Initializing device with implicit mTLS...")

        # 2. Create Device
        # The library will detect the missing keys and generate them in the
        # current directory.
        device = create_device(
            endpoint,
            client_config=ClientConfig(
                tls_config=TlsConfig(ca_certs=CA_CERT_FILE)
            )
        )

        logging.info(
            f"Device created. Check your directory for generated .pem files.")

        # 3. Run
        device.run()

    except KeyboardInterrupt:
        sys.exit(0)
