#!/bin/bash

if (( $# < 4 )); then
    echo $0 PROJECT_ID DATASET_ID LOCATION TRIGGER_TOPIC [--drop]
    exit
fi

PROJECT_ID=$1
DATASET_ID=$2
LOCATION=$3
TRIGGER_TOPIC=$4
shift 4



if [[ $1 == "--drop" ]]; then
    shift 1
    #echo "WARNING: Dropping tables in 5 seconds. Data will be permanently lost"
    #sleep 5 && echo "Deleting tables ..." && sleep 3
    bq rm -t -f $PROJECT_ID:$DATASET_ID.iot_connects
fi

FUNCTION_NAME=gcloud_iot_connection_log
TOPIC=iot_connections

# State table
bq mk \
    --table \
    $PROJECT_ID:$DATASET_ID.iot_connects \
    schema_iot_logs.json 

# Create pub/sub topic
gcloud pubsub topics create $TOPIC

# create logs router
gcloud logging sinks create iot_connections_logsink \
    pubsub.googleapis.com/projects/$PROJECT_ID/topics/$TOPIC \
    --log-filter='resource.type="gce_instance"'

LOGSINK_SERVICE_ACCOUNT=$(gcloud logging sinks describe iot_connections_logsink --project=$PROJECT_ID | grep writerIdentity | sed "s/writerIdentity: //")
gcloud pubsub topics add-iam-policy-binding $TOPIC --project=$PROJECT_ID --member=$LOGSINK_SERVICE_ACCOUNT --role='roles/pubsub.publisher'

# Deploy Cloud Function
gcloud functions deploy $FUNCTION_NAME \
    --trigger-topic=logtest\
    --entry-point=logConnectionEvents \
    --runtime nodejs16 \
    --project=$PROJECT_ID \
    --source=functions/ \
    --set-env-vars PROJECT_ID=$PROJECT_ID,DATASET_ID=$DATASET_ID
