{{- if .Values.dockerSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: 'docker-api-auth'
  annotations:
    description: "{{ .Chart.Description }}"
  labels:
    app: '{{ template "udmi-api.name" . }}'
    chart: '{{ template "udmi-api.chart" . }}'
    component: dockerconfigjson
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson.b64enc" . }}

{{- end }}
