apiVersion: v1
kind: Service
metadata:
  name: {{ include "udmi-api.fullname" . }}
  labels:
    {{- include "udmi-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4300
      protocol: TCP
      name: http
  selector:
    {{- include "udmi-api.selectorLabels" . | nindent 4 }}
