#!/bin/sh
set -o errexit -o nounset

MANGO_VERSION=5.1.4
mkdir -p mango/data && cd mango
curl -sSL https://store.mango-os.com/downloads/m2m2-udmi-${MANGO_VERSION}.zip -o udmi.zip
unzip udmi.zip -d udmi && rm udmi.zip

docker run --rm \
  -p 8443:8443 \
  -v data:/opt/mango-data \
  -v udmi:/opt/mango/web/modules/udmi \
  ghcr.io/radixiot/mango:${MANGO_VERSION}
